import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {startCRM} from '../src/crm.js';
test('la V1 en ligne sauvegarde vers le backend et affiche les pièces jointes distantes',async()=>{
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
 const dom=new JSDOM(html,{url:'https://crm.test/'});
 const saved=[];
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});
 const api=startCRM(null,{save:state=>saved.push(structuredClone(state)),putBlob:async()=>{},getBlob:async()=>new Blob(['test'],{type:'text/plain'})});
 document.querySelector('[data-view="tasks"]').click();
 document.querySelector('[data-add="tasks"]').click();
 const form=document.getElementById('editForm');form.elements.title.value='Test cloud';
 form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
 await new Promise(r=>setTimeout(r,0));
 assert.equal(saved.length,1);assert.equal(saved[0].tasks[0].title,'Test cloud');assert.equal(api.getState().tasks.length,1);
 assert.equal(dom.window.localStorage.getItem('lcs-crm-v1'),null);
 const remote=api.getState();remote.tasks[0].title='Autre membre';api.replaceState(remote);assert.match(document.getElementById('content').textContent,/Autre membre/);

 const state=api.getState();state.contacts=[{id:'c1',type:'Partenaire',company:'Test Société',first:'Alex',last:'Martin',email:'alex@example.test',phone:'0123456789'}];api.replaceState(state);
 document.querySelector('[data-view="partners"]').click();document.querySelector('[data-add="partners"]').click();
 const partner=document.getElementById('editForm');partner.elements.company.value='Test Société';partner.elements.company.dispatchEvent(new dom.window.Event('change',{bubbles:true}));
 assert.equal(partner.elements.name.value,'Alex Martin');assert.equal(partner.elements.email.value,'alex@example.test');assert.equal(partner.elements.phone.value,'0123456789');assert.ok(!partner.textContent.includes('Annuler'));
 document.querySelector('.close').click();document.querySelector('[data-view="posts"]').click();document.querySelector('[data-add="posts"]').click();
 const post=document.getElementById('editForm');for(const group of ['Presse','Web','RS']){post.elements.group.value=group;post.elements.group.dispatchEvent(new dom.window.Event('change',{bubbles:true}));assert.equal(post.elements.channel.disabled,group!=='RS');assert.equal(post.querySelector('[data-field="channel"]').hidden,group!=='RS')}
 document.querySelector('.close').click();document.getElementById('mobileToggle').click();assert.equal(document.getElementById('mobileToggle').getAttribute('aria-expanded'),'true');document.querySelector('#mobileNav [data-view="ideas"]').click();assert.equal(document.getElementById('mobileToggle').getAttribute('aria-expanded'),'false');

 const ledger=api.getState();ledger.ledger_entries=[];ledger.ledger_categories=[];ledger.invoices=[{id:'f',title:'Facture test',tag:'Facture',status:'Payé',amount:20},{id:'d',title:'Devis test',tag:'Devis',status:'Non payé',amount:30}];api.replaceState(ledger);
 document.querySelector('[data-view="bilan"]').click();document.querySelector('[data-bilan-category="sale"]').click();
 let b=document.getElementById('bilanCategoryForm');b.elements.title.value='Billetterie';b.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
 assert.equal(api.getState().ledger_categories[0].title,'Billetterie');
 document.querySelector('[data-bilan-add="sale"]').click();b=document.getElementById('bilanLineForm');b.elements.title.value='VIP';b.elements.amount.value='100.25';b.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
 assert.equal(api.getState().ledger_entries[0].amountCents,10025);
 let select=document.querySelector('[data-bilan-move]');select=document.querySelector('[data-bilan-move="'+api.getState().ledger_entries[0].id+'"]');select.value=api.getState().ledger_categories[0].id;select.dispatchEvent(new Event('change',{bubbles:true}));
 assert.equal(api.getState().ledger_entries[0].categoryId,api.getState().ledger_categories[0].id);
 b=document.getElementById('ncAccountForm');b.elements.amount.value='500';b.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));assert.equal(api.getState().settings.ncBalance,500);
 document.querySelector('[data-view="invoices"]').click();assert.match(document.querySelector('tbody').textContent,/Facture test/);assert.doesNotMatch(document.querySelector('tbody').textContent,/Devis test/);
 document.querySelector('[data-invoice-tab="Devis"]').click();assert.match(document.querySelector('tbody').textContent,/Devis test/);
 document.querySelector('[data-add="invoices"]').click();assert.equal(document.getElementById('editForm').elements.tag.value,'Devis');

 document.querySelector('.close').click();
 document.querySelector('[data-view="partners"]').click();document.querySelector('[data-add="partners"]').click();
 let pform=document.getElementById('editForm');pform.elements.name.value='Alex Martin';pform.elements.name.dispatchEvent(new Event('change',{bubbles:true}));assert.equal(pform.elements.company.value,'Test Société');
 const NativeFormData=globalThis.FormData;let uploads={};
 globalThis.FormData=class extends NativeFormData{constructor(form){super(form);for(const [key,files] of Object.entries(uploads)){this.delete(key);for(const file of files)this.append(key,file);}}};
 uploads={partnerInvoiceUpload:[new dom.window.File(['pdf'],'partenaire.pdf',{type:'application/pdf'})]};
 pform.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));uploads={};
 const partnerId=api.getState().partners[0].id;assert.equal(api.getState().invoices.filter(x=>x.partnerId===partnerId).length,1);
 document.querySelector('[data-view="exhibitors"]').click();document.querySelector('[data-exhibitor-tab="partners"]').click();document.querySelector('[data-row-edit="partners:'+partnerId+'"]').click();
 assert.match(document.querySelector('#overlay').textContent,/Facture · Test Société/);document.querySelector('.close').click();
 document.querySelector('[data-view="expenses"]').click();document.querySelector('#mobileToggle').click();document.querySelector('[data-add="expenses"]').click();
 assert.equal(document.querySelector('#mobileToggle').hidden,true);assert.equal(document.querySelector('#mobileToggle').getAttribute('aria-expanded'),'false');
 let exp=document.getElementById('editForm');exp.elements.title.value='Signalétique';exp.elements.receivedDate.value='2026-09-30';exp.elements.status.value='En impression';
 uploads={attachmentsUpload:[new dom.window.File(['pdf'],'plan.pdf',{type:'application/pdf'}),new dom.window.File(['image'],'visuel.png',{type:'image/png'})]};
 exp.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));uploads={};
 assert.equal(api.getState().expenses[0].attachments.length,2);assert.equal(api.getState().expenses[0].receivedDate,'2026-09-30');assert.equal(api.getState().expenses[0].status,'En impression');
 document.querySelector('[data-row-edit^="expenses:"]').click();exp=document.getElementById('editForm');exp.querySelector('[name="removeAttachment"]').checked=true;
 exp.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));assert.equal(api.getState().expenses[0].attachments.length,1);
 globalThis.FormData=NativeFormData;
 const program=api.getState();program.animations=[];api.replaceState(program);
 document.querySelector('[data-view="animations"]').click();
 assert.equal(document.querySelectorAll('.animation-hour').length,13);
 document.querySelector('[data-animation-slot="09:00"]').click();
 let animation=document.getElementById('editForm');assert.equal(animation.elements.start.value,'09:00');
 animation.elements.title.value='Animation basket';animation.elements.owner.value='';
 animation.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));
 assert.equal(api.getState().animations.length,1);assert.match(document.querySelector('.animation-event').textContent,/Animation basket/);
 document.querySelector('.animation-event').click();animation=document.getElementById('editForm');animation.elements.end.value='11:00';animation.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));
 assert.equal(api.getState().animations[0].end,'11:00');
 document.querySelector('[data-view="settings"]').click();assert.ok(document.querySelector('#accountSettings'));assert.ok(!document.querySelector('#refreshCloud'));assert.ok(!document.querySelector('.side-bottom'));
 dom.window.close();
});
