import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {startCRM} from '../src/crm.js';
import {simulateSpace} from '../src/space-simulator.js';
import {vipStatistics,vipKPIs} from '../src/vip-kpis.js';
import {bilanData} from '../src/bilan.js';
import {diffRecords} from '../src/records.js';
const user='00000000-0000-0000-0000-000000000001';
test('returning Oui/Non, non-réponses et camembert par catégorie',()=>{
 const rows=[{kind:'VIP',returning:'Oui',priority:'Basket'},{kind:'VIP',returning:' OUI ',priority:' basket '},{kind:'VIP',returning:'Non',priority:'Pokémon'},{kind:'VIP',returning:'',priority:''},{kind:'Early Access',returning:'Non',priority:'Foot'}];const vip=vipStatistics(rows,'VIP');assert.equal(vip.yes,2);assert.equal(vip.no,1);assert.equal(vip.missing,1);assert.ok(Math.abs(vip.yesPercent-200/3)<1e-9);assert.equal(vip.communityMissing,1);assert.equal(vip.communities[0].count,2);assert.ok(Math.abs(vip.communities.reduce((n,c)=>n+c.percent,0)-100)<1e-9);const early=vipStatistics(rows,'Early Access');assert.equal(early.yesPercent,0);assert.equal(early.noPercent,100);assert.equal(vipStatistics([],'VIP').yesPercent,null);const html=vipKPIs(rows,s=>String(s));assert.match(html,/Returning VIP/);assert.match(html,/Returning Early/);assert.match(html,/Communauté VIP/);assert.match(html,/conic-gradient/);
});
test('calcul monétaire, options sélectionnées, quantité et valeurs invalides',()=>{
 const config={priceSqm:19.99,options:[{id:'light',name:'Éclairage',price:20},{id:'ignored',name:'Mobilier',price:500}]};const result=simulateSpace(config,7.5,{light:{checked:true,quantity:3},ignored:{checked:false,quantity:9}});assert.equal(result.baseCents,14993);assert.equal(result.options.length,1);assert.equal(result.options[0].amountCents,6000);assert.equal(result.totalCents,20993);assert.equal(simulateSpace({priceSqm:'0,10'},3).totalCents,30);assert.equal(simulateSpace(config,-1,{light:{checked:true,quantity:-2}}).totalCents,0);assert.equal(simulateSpace(config,Infinity).baseCents,0);
});
test('location du Salon prioritaire, ancienne location conservée et zéro explicite',()=>{
 const db={settings:{},forecast2027:{hallRental:900},invoices:[],ledger_entries:[]};assert.equal(bilanData(db).expenses,90000);db.settings.hallRental=1200.50;let data=bilanData(db);assert.equal(data.expenses,120050);assert.equal(data.rows.filter(r=>r.sourceKind==='hall').length,1);assert.equal(data.rows.find(r=>r.sourceKind==='hall').categoryId,'expense-hall');db.settings.hallRental=0;assert.equal(bilanData(db).expenses,0);
});
async function setup(role='admin',overrides={}){const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/le-salon?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});const api=startCRM(null,{role,userId:user,members:[{member_id:user,first_name:'Alex',member_role:'admin'}],save:()=>{},...overrides});return {dom,api}}
const change=(selector,value)=>{const e=document.querySelector(selector);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatchEvent(new Event('change',{bubbles:true}))};
test('Salon : location vers Bilan, paramétrage, calcul, rattachement et historique figé',async()=>{
 const {dom,api}=await setup();const state=api.getState();state.ledger_entries=[];state.ledger_categories=[];state.partners=[{id:'p',company:'Studio',amount:200,amountForced:true}];state.exhibitors=[{id:'pro',company:'Pro',vendorType:'Pro',amount:150,amountEdited:true},{id:'private',first:'Particulier',vendorType:'Collectionneur'}];api.replaceState(state);const before=api.getState();change('[data-salon-number="hallRental"]','1234.50');assert.equal(bilanData(api.getState()).expenses,123450);assert.equal(api.getState().forecast2027.hallRental,1234.5);
 document.querySelector('[data-salon-tab="simulator"]').click();assert.equal(document.querySelectorAll('.space-simulator-grid>.panel').length,2);change('[data-space-rate]',50);document.querySelector('[data-space-option-add]').click();const option=api.getState().settings.spaceSimulator.options[0];change('[data-space-option-name]', 'Éclairage');change('[data-space-option-price]',20);change('[data-space-area]',8);change('[data-space-option-check]',true);change('[data-space-option-quantity]',3);assert.match(document.querySelector('.space-quote-summary').textContent,/460/);change('[data-space-link-id]','p');document.querySelector('[data-space-attach]').click();let saved=api.getState();assert.equal(saved.partners[0].amount,200);assert.equal(saved.partners[0].spaceQuotes[0].totalCents,46000);assert.equal(saved.partners[0].spaceQuotes[0].authorName,'Alex');change('[data-space-option-price]',30);assert.equal(api.getState().partners[0].spaceQuotes[0].totalCents,46000);change('[data-space-link-kind]','exhibitors');assert.equal(document.querySelector('[data-space-link-id]').options.length,2);change('[data-space-link-id]','pro');document.querySelector('[data-space-attach]').click();assert.equal(api.getState().exhibitors[0].amount,150);assert.equal(api.getState().exhibitors[0].spaceQuotes[0].totalCents,49000);document.querySelector('[data-space-option-delete]').click();assert.equal(api.getState().settings.spaceSimulator.options.length,0);assert.match(document.querySelector('.space-quote-summary').textContent,/400/);
 const changes=diffRecords(before,api.getState());assert.ok(changes.some(c=>c.entity==='settings'));assert.ok(changes.some(c=>c.entity==='partners'));assert.ok(changes.some(c=>c.entity==='exhibitors'));assert.ok(changes.every(c=>['settings','forecast','partners','exhibitors'].includes(c.entity)));
 document.querySelector('[data-view="partners"]').click();document.querySelector('[data-edit="partners:p"]').click();assert.match(document.getElementById('overlay').textContent,/Estimations d’espace/);assert.match(document.getElementById('overlay').textContent,/Éclairage/);dom.window.close();
});
test('compte en lecture seule : calcul possible, configuration et rattachement interdits',async()=>{
 const {dom,api}=await setup('viewer');document.querySelector('[data-salon-tab="simulator"]').click();assert.equal(document.querySelector('[data-space-rate]').disabled,true);assert.equal(document.querySelector('[data-space-option-add]'),null);assert.equal(document.querySelector('[data-space-attach]'),null);change('[data-space-area]',12);assert.match(document.querySelector('.space-quote-summary').textContent,/12 m²/);assert.equal(api.getState().settings.spaceSimulator,undefined);dom.window.close();
});
test('fiche partenaire : onglets, choix modifiable, annulation et plusieurs estimations',async()=>{
 const {dom,api}=await setup();let state=api.getState();state.partners=[{id:'p',company:'Studio',unit:'Table',quantity:2,amount:200,amountForced:true,status:'Accord',spaceQuotes:[{id:'q1',tables:3,area:8,priceSqmCents:5000,baseCents:40000,totalCents:46000,options:[{name:'Éclairage',quantity:3,unitCents:2000,amountCents:6000}],createdAt:'2026-10-09T12:00:00Z',authorName:'Alex'},{id:'q2',tables:4,area:10,priceSqmCents:5000,baseCents:50000,totalCents:50000,options:[],createdAt:'2026-10-09T12:00:00Z',authorName:'Alex'}]}];api.replaceState(state);document.querySelector('[data-view="partners"]').click();document.querySelector('[data-edit="partners:p"]').click();let form=document.getElementById('editForm');assert.equal(document.querySelectorAll('[role=tab]').length,4);document.querySelector('#partner-tab-1').click();assert.equal(document.getElementById('partner-panel-1').hidden,false);assert.equal(form.elements.tables.value,'2');assert.equal(form.elements.area.value,'0');assert.equal(form.elements.status.value,'Accord');assert.equal(form.elements.status.getAttribute('form'),'editForm');change('[name=quoteChoice][value=q1]', 'q1');assert.equal(form.elements.amount.value,'460');assert.equal(form.elements.tables.value,'3');assert.equal(form.elements.area.value,'8');form.elements.amount.value='475';form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));assert.equal(api.getState().partners[0].amount,475);assert.equal(api.getState().partners[0].activeSpaceQuoteId,'q1');assert.equal(api.getState().partners[0].quantity,8);
 document.querySelector('[data-edit="partners:p"]').click();form=document.getElementById('editForm');document.querySelector('[data-quote-cancel=q1]').click();assert.equal(form.elements.amount.value,'200');assert.equal(form.elements.tables.value,'2');assert.equal(document.querySelector('[name=quoteChoice][value=q1]').disabled,true);change('[name=quoteChoice][value=q2]','q2');assert.equal(form.elements.amount.value,'500');form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));state=api.getState();assert.equal(state.partners[0].spaceQuotes.length,2);assert.ok(state.partners[0].spaceQuotes[0].cancelledAt);assert.equal(state.partners[0].activeSpaceQuoteId,'q2');assert.equal(state.partners[0].tables,4);assert.equal(state.partners[0].area,10);dom.window.close();
});
test('tâches : séparation terminé et filtres personnels sous la recherche',async()=>{
 const {dom,api}=await setup();const state=api.getState();state.tasks=[{id:'todo',title:'Préparer',status:'À faire',assigneeId:user},{id:'progress',title:'Installer',status:'En cours',assigneeId:user},{id:'wait',title:'Attendre devis',status:'En attente',assigneeId:user},{id:'done',title:'Clôturer',status:'Terminée',assigneeId:user},{id:'other',title:'Autre membre',status:'Terminée',assigneeId:'other'}];api.replaceState(state);document.querySelector('[data-view="mytasks"]').click();assert.equal(document.querySelectorAll('table.data tbody tr').length,3);const search=document.querySelector('#search'),statuses=document.querySelector('.task-status-filters');assert.ok(search.compareDocumentPosition(statuses)&dom.window.Node.DOCUMENT_POSITION_FOLLOWING);document.querySelector('[data-my-task-status="En attente"]').click();assert.equal(document.querySelectorAll('table.data tbody tr').length,1);assert.match(document.querySelector('table.data').textContent,/Attendre devis/);document.querySelector('[data-task-scope=mine][data-scope-value=done]').click();assert.equal(document.querySelectorAll('table.data tbody tr').length,1);assert.match(document.querySelector('table.data').textContent,/Clôturer/);assert.doesNotMatch(document.querySelector('table.data').textContent,/Autre membre/);document.querySelector('[data-view="tasks"]').click();document.querySelector('[data-task-scope=backlog][data-scope-value=done]').click();assert.equal(document.querySelectorAll('table.data tbody tr').length,2);dom.window.close();
});
test('logo partenaire hydraté dès ouverture et tags de statut/communauté',async()=>{
 let called=0;const {dom,api}=await setup('admin',{getBlob:async()=>{called++;return new Blob(['image'],{type:'image/png'})}});const state=api.getState();state.partners=[{id:'p',company:'Studio',logoId:'logo',community:'Basket',status:'Refusé'}];api.replaceState(state);document.querySelector('[data-view="partners"]').click();document.querySelector('[data-edit="partners:p"]').click();await new Promise(resolve=>setTimeout(resolve,0));const header=document.querySelector('.partner-record-header');assert.ok(called>=2);assert.match(header.querySelector('.partner-record-logo').src,/^blob:/);assert.equal(header.querySelector('.partner-record-logo').dataset.blobId,'logo');assert.match(header.querySelector('.partner-status-tag').className,/refused/);assert.match(header.querySelector('.community-tag').className,/basket/);dom.window.close();
});
test('assets partenaires : uploads multiples et téléchargement des fichiers existants',async()=>{
 const uploaded=[];const {dom,api}=await setup('admin',{putBlob:async(id,file)=>uploaded.push({id,name:file.name})});const state=api.getState();state.partners=[{id:'p',company:'Studio',logoId:'logo',partnerAssets:[{blobId:'old',category:'charte',fileName:'Charte existante.pdf'}]}];api.replaceState(state);document.querySelector('[data-view="partners"]').click();document.querySelector('[data-edit="partners:p"]').click();document.querySelector('#partner-tab-2').click();assert.equal(document.querySelector('[data-blob-download=logo]').textContent,'Télécharger le logo');assert.ok(document.querySelector('[data-blob-download=old]'));assert.equal(document.querySelector('[name=partnerLogoHDUpload]').multiple,true);const form=document.getElementById('editForm'),Original=globalThis.FormData;globalThis.FormData=class extends Original{constructor(f){super(f);if(f===form){this.delete('partnerLogoHDUpload');this.append('partnerLogoHDUpload',new dom.window.File(['png'],'Logo HD.png',{type:'image/png'}));this.append('partnerLogoHDUpload',new dom.window.File(['pdf'],'Logo HD.pdf',{type:'application/pdf'}));this.delete('partnerCharteUpload');this.append('partnerCharteUpload',new dom.window.File(['pdf'],'Charte.pdf',{type:'application/pdf'}));this.delete('partnerOtherAssetsUpload');for(let i=0;i<12;i++)this.append('partnerOtherAssetsUpload',new dom.window.File(['doc'],'Document '+i+'.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));}}};try{form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));const row=api.getState().partners[0];assert.equal(uploaded.length,15);assert.equal(row.partnerAssets.length,16);assert.equal(row.partnerAssets.filter(a=>a.category==='divers').length,12);assert.equal(row.logoId,'logo');assert.equal(row.partnerAssets.filter(a=>a.category==='logo-hd').length,2);assert.equal(row.partnerLogoHDUpload,undefined);document.querySelector('[data-edit="partners:p"]').click();assert.ok(document.querySelector(`[data-blob-download="${row.partnerAssets[1].blobId}"]`));}finally{globalThis.FormData=Original;dom.window.close()}
});
test('connexion sur Contacts avec un carnet rempli : démarrage sans erreur',async()=>{
 const fixture=await setup();const state=fixture.api.getState();fixture.dom.window.close();state.contacts=[{id:'contact',company:'Studio',first:'Alex',last:'Martin',email:'contact@example.test',type:'Partenaire'}];const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/contacts?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});try{assert.doesNotThrow(()=>startCRM(state,{role:'admin',userId:user,members:[],save:()=>{}}));assert.match(document.querySelector('#content').textContent,/Alex/);assert.match(document.querySelector('#content').textContent,/Studio/);}finally{dom.window.close()}
});
