import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {startCRM} from '../src/crm.js';
import {simulateSpace} from '../src/space-simulator.js';
import {vipStatistics,vipKPIs} from '../src/vip-kpis.js';
import {bilanData} from '../src/bilan.js';
import {diffRecords} from '../src/records.js';
const user='00000000-0000-0000-0000-000000000001';
test('returning Oui/Non, non-réponses et camembert par catégorie',()=>{
 const rows=[{kind:'VIP',returning:'Oui',priority:'Basket'},{kind:'VIP',returning:' OUI ',priority:' basket '},{kind:'VIP',returning:'Non',priority:'Pokémon'},{kind:'VIP',returning:'',priority:''},{kind:'Early Access',returning:'Non',priority:'Foot'}];const vip=vipStatistics(rows,'VIP');assert.equal(vip.yes,2);assert.equal(vip.no,1);assert.equal(vip.missing,1);assert.ok(Math.abs(vip.yesPercent-200/3)<1e-9);assert.equal(vip.communityMissing,1);assert.equal(vip.communities[0].count,2);assert.ok(Math.abs(vip.communities.reduce((n,c)=>n+c.percent,0)-100)<1e-9);const early=vipStatistics(rows,'Early Access');assert.equal(early.yesPercent,0);assert.equal(early.noPercent,100);assert.equal(vipStatistics([],'VIP').yesPercent,null);const html=vipKPIs(rows,s=>String(s));assert.match(html,/Returning VIP/);assert.match(html,/Returning Early/);assert.match(html,/Communauté VIP/);assert.match(html,/conic-gradient/);
});
test('calcul monétaire, options sélectionnées, quantité et valeurs invalides',()=>{
 const config={priceSqm:19.99,options:[{id:'light',name:'Éclairage',price:20},{id:'ignored',name:'Mobilier',price:500}]};const result=simulateSpace(config,7.5,{light:{checked:true,quantity:3},ignored:{checked:false,quantity:9}});assert.equal(result.baseCents,14993);assert.equal(result.options.length,1);assert.equal(result.options[0].amountCents,6000);assert.equal(result.totalCents,20993);assert.equal(simulateSpace({priceSqm:'0,10'},3).totalCents,30);assert.equal(simulateSpace(config,-1,{light:{checked:true,quantity:-2}}).totalCents,0);assert.equal(simulateSpace(config,Infinity).baseCents,0);
});
test('location du Salon prioritaire, ancienne location conservée et zéro explicite',()=>{
 const db={settings:{},forecast2027:{hallRental:900},invoices:[],ledger_entries:[]};assert.equal(bilanData(db).expenses,90000);db.settings.hallRental=1200.50;let data=bilanData(db);assert.equal(data.expenses,120050);assert.equal(data.rows.filter(r=>r.sourceKind==='hall').length,1);assert.equal(data.rows.find(r=>r.sourceKind==='hall').categoryId,'expense-hall');db.settings.hallRental=0;assert.equal(bilanData(db).expenses,0);
});
async function setup(role='admin'){const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/le-salon?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});const api=startCRM(null,{role,userId:user,members:[{member_id:user,first_name:'Alex',member_role:'admin'}],save:()=>{}});return {dom,api}}
const change=(selector,value)=>{const e=document.querySelector(selector);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatchEvent(new Event('change',{bubbles:true}))};
test('Salon : location vers Bilan, paramétrage, calcul, rattachement et historique figé',async()=>{
 const {dom,api}=await setup();const state=api.getState();state.ledger_entries=[];state.ledger_categories=[];state.partners=[{id:'p',company:'Studio',amount:200,amountForced:true}];state.exhibitors=[{id:'pro',company:'Pro',vendorType:'Pro',amount:150,amountEdited:true},{id:'private',first:'Particulier',vendorType:'Collectionneur'}];api.replaceState(state);const before=api.getState();change('[data-salon-number="hallRental"]','1234.50');assert.equal(bilanData(api.getState()).expenses,123450);assert.equal(api.getState().forecast2027.hallRental,1234.5);
 document.querySelector('[data-salon-tab="simulator"]').click();assert.equal(document.querySelectorAll('.space-simulator-grid>.panel').length,2);change('[data-space-rate]',50);document.querySelector('[data-space-option-add]').click();const option=api.getState().settings.spaceSimulator.options[0];change('[data-space-option-name]', 'Éclairage');change('[data-space-option-price]',20);change('[data-space-area]',8);change('[data-space-option-check]',true);change('[data-space-option-quantity]',3);assert.match(document.querySelector('.space-quote-summary').textContent,/460/);change('[data-space-link-id]','p');document.querySelector('[data-space-attach]').click();let saved=api.getState();assert.equal(saved.partners[0].amount,200);assert.equal(saved.partners[0].spaceQuotes[0].totalCents,46000);assert.equal(saved.partners[0].spaceQuotes[0].authorName,'Alex');change('[data-space-option-price]',30);assert.equal(api.getState().partners[0].spaceQuotes[0].totalCents,46000);change('[data-space-link-kind]','exhibitors');assert.equal(document.querySelector('[data-space-link-id]').options.length,2);change('[data-space-link-id]','pro');document.querySelector('[data-space-attach]').click();assert.equal(api.getState().exhibitors[0].amount,150);assert.equal(api.getState().exhibitors[0].spaceQuotes[0].totalCents,49000);document.querySelector('[data-space-option-delete]').click();assert.equal(api.getState().settings.spaceSimulator.options.length,0);assert.match(document.querySelector('.space-quote-summary').textContent,/400/);
 const changes=diffRecords(before,api.getState());assert.ok(changes.some(c=>c.entity==='settings'));assert.ok(changes.some(c=>c.entity==='partners'));assert.ok(changes.some(c=>c.entity==='exhibitors'));assert.ok(changes.every(c=>['settings','forecast','partners','exhibitors'].includes(c.entity)));
 document.querySelector('[data-view="partners"]').click();document.querySelector('[data-edit="partners:p"]').click();assert.match(document.getElementById('overlay').textContent,/Estimations d’espace/);assert.match(document.getElementById('overlay').textContent,/Éclairage/);dom.window.close();
});
test('compte en lecture seule : calcul possible, configuration et rattachement interdits',async()=>{
 const {dom,api}=await setup('viewer');document.querySelector('[data-salon-tab="simulator"]').click();assert.equal(document.querySelector('[data-space-rate]').disabled,true);assert.equal(document.querySelector('[data-space-option-add]'),null);assert.equal(document.querySelector('[data-space-attach]'),null);change('[data-space-area]',12);assert.match(document.querySelector('.space-quote-summary').textContent,/12 m²/);assert.equal(api.getState().settings.spaceSimulator,undefined);dom.window.close();
});
