import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {questions,validateAnswers} from '../src/survey-schema.js';
import {surveyStats,themesFor} from '../src/survey-results.js';
const wid='10000000-0000-0000-0000-000000000001',uid='00000000-0000-0000-0000-000000000001';
const migration=await readFile(new URL('../supabase/migrations/009_surveys.sql',import.meta.url),'utf8');
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;
create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table crm_workspaces(id uuid primary key,name text,created_at timestamptz default now());
create table crm_members(workspace_id uuid,user_id uuid,role text);
create table crm_editions(workspace_id uuid,year integer,primary key(workspace_id,year));
create function crm_has_role(w text,roles text[]) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.crm_members where workspace_id::text=w and user_id=auth.uid() and role=any(roles))$$;
insert into auth.users values('${uid}');insert into crm_workspaces(id,name) values('${wid}','LCS');insert into crm_editions values('${wid}',2026);insert into crm_members values('${wid}','${uid}','admin');
select set_config('request.jwt.claim.sub','${uid}',false);`);await db.exec(migration);return db;}
test('questionnaire : embranchement exposant et regroupement de paraphrases',()=>{
 assert.ok(questions.exposant.at(-1).key==='identity');
 assert.ok(validateAnswers('visiteur',{community:'Basket',duration:'1 à 2 heures',purchase:'Non',satisfaction:0,returnIntent:'Oui'}));
 assert.ok(!validateAnswers('exposant',{participation:'Exposant',setup:3,attendance:4,value:4,roi:2,satisfaction:4,returnIntent:'Oui'}));
 assert.ok(validateAnswers('exposant',{participation:'Partenaire',setup:3,attendance:4,value:4,roi:2,satisfaction:4,returnIntent:'Oui'}));
 for(const phrase of ['Trop de monde dans les allées','Les allées étaient pleines','L’affluence était trop forte'])assert.ok(themesFor(phrase).includes('Circulation et affluence'));
 assert.equal(surveyStats([{answers:{satisfaction:0}},{answers:{satisfaction:5}}]).average,2.5);
});
test('soumission publique anonyme, lecture membres et isolation par année',async()=>{const db=await setup();try{
 await db.exec('set role anon');
 assert.equal((await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result.year,2026);
 const answers={community:'Basket',duration:'1 à 2 heures',purchase:'Non',satisfaction:0,returnIntent:'Oui',improvements:'Trop de monde dans les allées'};
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[answers]);
 const exposant={participation:'Exposant',vendorType:'Professionnel',community:'Basket',zone:'Basket',setup:3,attendance:4,value:5,roi:0,satisfaction:4,returnIntent:'Oui',highlights:'Accueil',improvements:'Affluence',identity:''};
 await db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[exposant]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2025,'visiteur',$1)",[answers]),e=>e.code==='22023');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{...answers,identity:'un nom'}]),e=>e.code==='22023');
 await assert.rejects(db.query('select * from crm_survey_responses'),e=>e.code==='42501');
 await assert.rejects(db.query(`select crm_survey_results('${wid}',2026)`),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 const records=(await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result;
 assert.equal(records.length,2);assert.equal(records.find(r=>r.type==='visiteur').answers.satisfaction,0);
 await db.exec('reset role');await db.exec('create table if not exists dummy(x integer)');
 await db.query('insert into crm_editions values($1,2027)',[wid]);await db.exec('set role anon');
 assert.equal((await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result.year,2027);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[answers]),e=>e.code==='22023');
 }finally{await db.close()}});
const editorMigration=await readFile(new URL('../supabase/migrations/010_survey_editor.sql',import.meta.url),'utf8');
test('édition par année, soumission exposant, sécurité et suppression ciblée',async()=>{const db=await setup();try{
 await db.exec('alter table crm_editions add column closed_at timestamptz');
 await db.exec(editorMigration);
 await db.exec('set role anon');
 const exposition={participation:'Exposant',vendorType:'Professionnel',community:'Basket',zone:'Basket',setup:3,attendance:4,value:5,roi:0,satisfaction:4,returnIntent:'Oui',identity:''};
 const id=(await db.query("select crm_submit_survey('lcs',2026,'exposant',$1) as id",[exposition])).rows[0].id;
 await assert.rejects(db.query('select * from crm_survey_forms'),e=>e.code==='42501');
 await assert.rejects(db.query('select crm_survey_delete_response($1,2026,$2)',[wid,id]),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 const schema=[{key:'satisfaction',label:'Ta note',kind:'rating',required:true},{key:'customOne',label:'Quelle zone ?',kind:'dropdown',options:['Basket','Soccer'],required:true}];
 assert.equal((await db.query("select crm_survey_save_form($1,2026,'exposant',0,$2) as version",[wid,schema])).rows[0].version,1);
 await assert.rejects(db.query("select crm_survey_save_form($1,2026,'exposant',0,$2)",[wid,schema]),e=>e.code==='40001');
 await db.exec('reset role');await db.exec('set role anon');
 const info=(await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result;
 assert.equal(info.forms.exposant.questions[1].label,'Quelle zone ?');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:4,customOne:'Invalid'}]),e=>e.code==='22023');
 const next=(await db.query("select crm_submit_survey('lcs',2026,'exposant',$1) as id",[{satisfaction:4,customOne:'Basket'}])).rows[0].id;
 await db.exec('reset role');await db.exec('set role authenticated');
 const rows=(await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result;
 assert.equal(rows.find(r=>r.id===next).questions[1].label,'Quelle zone ?');
 const extended=[...schema,{key:'customMany',label:'Plusieurs choix',kind:'checkbox',options:['A','B'],required:true},{key:'visitDay',label:'Date',kind:'date',required:false},{key:'count',label:'Nombre',kind:'number',required:false}];
 await db.query("select crm_survey_save_form($1,2026,'exposant',1,$2)",[wid,extended]);
 await db.exec('reset role');await db.exec('set role anon');
 await db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:3,customOne:'Soccer',customMany:['A','B'],visitDay:'2026-10-03',count:7}]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:3,customOne:'Soccer',customMany:['C']}]),e=>e.code==='22023');
 await db.exec('reset role');await db.exec('set role authenticated');
 await db.query('select crm_survey_delete_response($1,2026,$2)',[wid,id]);
 assert.equal((await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result.length,2);
 }finally{await db.close()}});
test('éditeur : ajout, options, ordre et affichage filtré',async()=>{
 const {JSDOM}=await import('jsdom');
 const {createEditor,renderSurveyEditor}=await import('../src/survey-editor.js');
 const {surveyResultsMarkup}=await import('../src/survey-results.js');
 const dom=new JSDOM('<div id="editor"></div>');
 const host=dom.window.document.getElementById('editor');
 const state=createEditor('visiteur');
 renderSurveyEditor(host,state,{onSave:async()=>{},onClose:()=>{}});
 host.querySelector('[data-survey-add]').click();
 assert.equal(state.items.at(-1).label,'Nouvelle question');
 const last=state.items.length-1;
 host.querySelector(`[data-index="${last}"][data-prop="label"]`).value='Notre nouvelle question';
 host.querySelector(`[data-index="${last}"][data-prop="label"]`).dispatchEvent(new dom.window.Event('input'));
 host.querySelector(`[data-survey-up="${last}"]`).click();
 assert.equal(state.items.at(-2).label,'Notre nouvelle question');
 const rows=[{id:'1',type:'visiteur',created_at:'2026-10-04T00:00:00Z',answers:{community:'Basket',satisfaction:5,highlights:'Bonne ambiance'}},{id:'2',type:'visiteur',created_at:'2026-10-04T00:00:00Z',answers:{community:'TCG',satisfaction:1,improvements:'Trop de monde'}}];
 assert.match(surveyResultsMarkup(rows,'all',2026,{community:'Basket'}),/Vue Basket · 1 réponses/);
 assert.doesNotMatch(surveyResultsMarkup(rows,'all',2026,{community:'Basket'}),/Trop de monde/);
 dom.window.close();
});
const brandingSQL=await readFile(new URL('../supabase/migrations/011_edition_branding.sql',import.meta.url),'utf8');
test('logo annuel public, upload réservé aux membres de l’édition ouverte',async()=>{const db=await setup();try{
 await db.exec(`alter table crm_editions add column closed_at timestamptz;
 create table crm_settings(workspace_id uuid,edition_year integer,id text,payload jsonb);
 create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(bucket_id text,name text);
 create function storage.foldername(path text) returns text[] language sql immutable as $$select string_to_array(regexp_replace(path,'/[^/]*$',''),'/')$$;
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;
 grant select on crm_editions to authenticated;
 grant insert on storage.objects to authenticated;
 insert into crm_settings values('${wid}',2026,'main','{"logoPath":"${wid}/2026/00000000-0000-0000-0000-000000000002.png"}');`);
 await db.exec(editorMigration);await db.exec(brandingSQL);
 await db.exec('set role anon');
 const info=(await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result;
 assert.equal(info.logo,`${wid}/2026/00000000-0000-0000-0000-000000000002.png`);
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[info.logo]),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 await db.query("insert into storage.objects values('lcs-branding',$1)",[info.logo]);
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[`${wid}/2027/00000000-0000-0000-0000-000000000003.png`]),e=>e.code==='42501');
 await db.exec('reset role');await db.query(`update crm_editions set closed_at=now() where workspace_id='${wid}' and year=2026`);await db.exec('set role authenticated');
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[`${wid}/2026/00000000-0000-0000-0000-000000000004.png`]),e=>e.code==='42501');
 }finally{await db.close()}});
