import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {questions,validateAnswers} from '../src/survey-schema.js';
import {surveyStats,themesFor} from '../src/survey-results.js';
import {visitorStats,visitorFeedbackMarkup,normalizeCity,matchesCommunity} from '../src/visitor-feedback.js';
import {buildSurveyCSV} from '../src/survey-editor.js';
const wid='10000000-0000-0000-0000-000000000001',uid='00000000-0000-0000-0000-000000000001';
const migration=await readFile(new URL('../supabase/migrations/009_surveys.sql',import.meta.url),'utf8');
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;
create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table crm_workspaces(id uuid primary key,name text,created_at timestamptz default now());
create table crm_members(workspace_id uuid,user_id uuid,role text);
create table crm_editions(workspace_id uuid,year integer,primary key(workspace_id,year));
create function crm_has_role(w text,roles text[]) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.crm_members where workspace_id::text=w and user_id=auth.uid() and role=any(roles))$$;
insert into auth.users values('${uid}');insert into crm_workspaces(id,name) values('${wid}','LCS');insert into crm_editions values('${wid}',2026);insert into crm_members values('${wid}','${uid}','admin');
select set_config('request.jwt.claim.sub','${uid}',false);`);await db.exec(migration);return db;}
test('questionnaire : embranchement exposant et regroupement de paraphrases',()=>{
 assert.equal(questions.exposant.length,27);
 assert.equal(questions.exposant[17].key,'q18_no_return_reason');
 assert.deepEqual(questions.exposant[17].showIf.anyOf,['Probablement pas','Non']);
 assert.ok(validateAnswers('visiteur',{community:'Basket',duration:'1 à 2 heures',purchase:'Non',satisfaction:0,returnIntent:'Oui'}));
 assert.ok(!validateAnswers('exposant',{q1_status:'Professionnel',q2_zone:'Basketball'}));
 const valid={q1_status:'Professionnel',q2_zone:'Basketball',q3_experience:9,q4_location:8,q5_space_fit:'Adapté',q6_space_limit:'Non',q7_logistics:Object.fromEntries(questions.exposant[6].rows.map(row=>[row,'4'])),q8_flow:'Bon',q9_crowding:'Non',q10_buying_type:'Un mélange assez équilibré',q11_card_budget:'50 à 100 €',q12_best_sellers:['Singles milieu de gamme','Cartes gradées'],q13_revenue:'1 000 à 2 000 €',q14_sales_expectations:'Conformes à mes attentes',q15_value:8,q16_organization:Object.fromEntries(questions.exposant[15].rows.map(row=>[row,'5'])),q17_return:'Oui, probablement',q19_next_config:['Plus de tables'],q20_booking_choice:'Non',q24_budget_increase:'Peut-être, selon le tarif'};
 assert.ok(validateAnswers('exposant',valid));
 assert.ok(validateAnswers('exposant',{...valid,q17_return:'Non',q18_no_return_reason:['Tarif']}));
 assert.ok(!validateAnswers('exposant',{...valid,q17_return:'Non'}));
 for(const phrase of ['Trop de monde dans les allées','Les allées étaient pleines','L’affluence était trop forte'])assert.ok(themesFor(phrase).includes('Forte affluence'));
 assert.equal(surveyStats([{answers:{satisfaction:0}},{answers:{satisfaction:5}}]).average,2.5);
});
test('dashboard visiteur publié : communautés multiples, ville normalisée, grille et note sur 10',()=>{
 const questions=[{key:'q_comm',label:'A quelle(s) communauté(s) appartiens-tu ?',kind:'checkbox'},
  {key:'q_age',label:"Quel est ta tranche d'âge ?",kind:'dropdown'},
  {key:'q_gender',label:'Quel est ton genre ?',kind:'choice'},
  {key:'q_city',label:'De quelle ville viens-tu ?',kind:'short'},
  {key:'q_grid',label:'Que penses-tu de',kind:'grid',rows:["la DATE de l'évènement",'La SALLE, le lieu'],columns:['Très satisfaisant','Satisfaisant',"Je n'ai pas vu"]},
  {key:'q_score',label:'Quelle note globale donnerais-tu au salon ?',kind:'rating10'},
  {key:'q_return',label:'Aurais-tu envie de revenir à la prochaine édition ?',kind:'choice'},
  {key:'q_dream',label:"C'est ton moment ! Qu'est-ce que tu RÊVES D'AVOIR pour l'édition 2027 ?",kind:'text'}];
 const row=(city,score,communities)=>({type:'visiteur',created_at:'2026-10-04T12:00:00Z',questions,answers:{q_comm:communities,q_age:'25 - 29 ans',q_gender:'Femme',q_city:city,q_grid:{"la DATE de l'évènement":'Très satisfaisant','La SALLE, le lieu':'Satisfaisant'},q_score:score,q_return:'Oui',q_dream:'Plus de cartes'}});
 const rows=[row('Boulogne sur mer',10,['Basket','Tcg (Pokemon, Lorcana, Magic ...)']),row('Boulogne-sur-mer',8,['Basket']),row('BOULOGNE SUR MER',6,['Soccer'])];
 const stats=visitorStats(rows,questions);
 assert.equal(normalizeCity('Boulogne-Sur-Mer'),normalizeCity('Boulogne sur mer'));
 assert.equal(stats.cities[0].count,3);
 assert.equal(stats.cities.length,1);
 assert.equal(stats.score,8);
 assert.deepEqual(stats.distributions.community,[['Basket',2],['Soccer',1],['TCG',1]]);
 assert.equal(stats.grid[0].counts[0].count,3);
 assert.equal(matchesCommunity(rows[0],'TCG'),true);
 const markup=visitorFeedbackMarkup(rows,questions);
 assert.match(markup,/Top 10 des villes/);
 assert.match(markup,/Tranches d’âge/);
 assert.match(markup,/Q20 · Retours libres/);
 assert.match(markup,/8,0\/10/);
});
test('soumission publique anonyme, lecture membres et isolation par année',async()=>{const db=await setup();try{
 await db.exec('set role anon');
 assert.equal((await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result.year,2026);
 const answers={community:'Basket',duration:'1 à 2 heures',purchase:'Non',satisfaction:0,returnIntent:'Oui',improvements:'Trop de monde dans les allées'};
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[answers]);
 const exposant={participation:'Exposant',vendorType:'Professionnel',community:'Basket',zone:'Basket',setup:3,attendance:4,value:5,roi:0,satisfaction:4,returnIntent:'Oui',highlights:'Accueil',improvements:'Affluence',identity:''};
 await db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[exposant]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2025,'visiteur',$1)",[answers]),e=>e.code==='22023');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{...answers,identity:'un nom'}]),e=>e.code==='22023');
 await assert.rejects(db.query('select * from crm_survey_responses'),e=>e.code==='42501');
 await assert.rejects(db.query(`select crm_survey_results('${wid}',2026)`),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 const records=(await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result;
 assert.equal(records.length,2);assert.equal(records.find(r=>r.type==='visiteur').answers.satisfaction,0);
 await db.exec('reset role');await db.exec('create table if not exists dummy(x integer)');
 await db.query('insert into crm_editions values($1,2027)',[wid]);await db.exec('set role anon');
 assert.equal((await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result.year,2027);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[answers]),e=>e.code==='22023');
 }finally{await db.close()}});
const editorMigration=await readFile(new URL('../supabase/migrations/010_survey_editor.sql',import.meta.url),'utf8');
test('édition par année, soumission exposant, sécurité et suppression ciblée',async()=>{const db=await setup();try{
 await db.exec('alter table crm_editions add column closed_at timestamptz');
 await db.exec(editorMigration);
 await db.exec('set role anon');
 const exposition={participation:'Exposant',vendorType:'Professionnel',community:'Basket',zone:'Basket',setup:3,attendance:4,value:5,roi:0,satisfaction:4,returnIntent:'Oui',identity:''};
 const id=(await db.query("select crm_submit_survey('lcs',2026,'exposant',$1) as id",[exposition])).rows[0].id;
 await assert.rejects(db.query('select * from crm_survey_forms'),e=>e.code==='42501');
 await assert.rejects(db.query('select crm_survey_delete_response($1,2026,$2)',[wid,id]),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 const schema=[{key:'satisfaction',label:'Ta note',kind:'rating',required:true},{key:'customOne',label:'Quelle zone ?',kind:'dropdown',options:['Basket','Soccer'],required:true}];
 assert.equal((await db.query("select crm_survey_save_form($1,2026,'exposant',0,$2) as version",[wid,schema])).rows[0].version,1);
 await assert.rejects(db.query("select crm_survey_save_form($1,2026,'exposant',0,$2)",[wid,schema]),e=>e.code==='40001');
 await db.exec('reset role');await db.exec('set role anon');
 const info=(await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result;
 assert.equal(info.forms.exposant.questions[1].label,'Quelle zone ?');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:4,customOne:'Invalid'}]),e=>e.code==='22023');
 const next=(await db.query("select crm_submit_survey('lcs',2026,'exposant',$1) as id",[{satisfaction:4,customOne:'Basket'}])).rows[0].id;
 await db.exec('reset role');await db.exec('set role authenticated');
 const rows=(await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result;
 assert.equal(rows.find(r=>r.id===next).questions[1].label,'Quelle zone ?');
 const extended=[...schema,{key:'customMany',label:'Plusieurs choix',kind:'checkbox',options:['A','B'],required:true},{key:'visitDay',label:'Date',kind:'date',required:false},{key:'count',label:'Nombre',kind:'number',required:false}];
 await db.query("select crm_survey_save_form($1,2026,'exposant',1,$2)",[wid,extended]);
 await db.exec('reset role');await db.exec('set role anon');
 await db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:3,customOne:'Soccer',customMany:['A','B'],visitDay:'2026-10-03',count:7}]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'exposant',$1)",[{satisfaction:3,customOne:'Soccer',customMany:['C']}]),e=>e.code==='22023');
 await db.exec('reset role');await db.exec('set role authenticated');
 await db.query('select crm_survey_delete_response($1,2026,$2)',[wid,id]);
 assert.equal((await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result.length,2);
 }finally{await db.close()}});
test('éditeur : ajout, options, ordre et affichage filtré',async()=>{
 const {JSDOM}=await import('jsdom');
 const {createEditor,renderSurveyEditor}=await import('../src/survey-editor.js');
 const {surveyResultsMarkup}=await import('../src/survey-results.js');
 const dom=new JSDOM('<div id="editor"></div>');
 const host=dom.window.document.getElementById('editor');
 const state=createEditor('visiteur');
 renderSurveyEditor(host,state,{onSave:async()=>{},onClose:()=>{}});
 host.querySelector('[data-survey-add]').click();
 assert.equal(state.items.at(-1).label,'Nouvelle question');
 const last=state.items.length-1;
 host.querySelector(`[data-index="${last}"][data-prop="label"]`).value='Notre nouvelle question';
 host.querySelector(`[data-index="${last}"][data-prop="label"]`).dispatchEvent(new dom.window.Event('input'));
 host.querySelector(`[data-survey-up="${last}"]`).click();
 assert.equal(state.items.at(-2).label,'Notre nouvelle question');
 let kind=host.querySelector(`[data-index="${last-1}"][data-prop="kind"]`);kind.value='grid';kind.dispatchEvent(new dom.window.Event('input'));kind.dispatchEvent(new dom.window.Event('change'));
 assert.equal(state.items.at(-2).label,'Notre nouvelle question');
 assert.deepEqual(state.items.at(-2).columns,['Très satisfaisant','Satisfaisant','Peu satisfaisant','Insatisfaisant','Je n’ai pas vu']);
 assert.equal(state.items.at(-2).rows.length,8);
 let gridRow=host.querySelector(`[data-grid-row-index="${last-1}"][data-grid-row="0"]`);gridRow.value='Accueil';gridRow.dispatchEvent(new dom.window.Event('input'));
 assert.equal(state.items.at(-2).rows[0],'Accueil');
 host.querySelector(`[data-grid-row-add="${last-1}"]`).click();
 assert.equal(state.items.at(-2).rows.length,9);
 gridRow=host.querySelector(`[data-grid-row-index="${last-1}"][data-grid-row="8"]`);gridRow.value='Signalétique';gridRow.dispatchEvent(new dom.window.Event('input'));
 assert.equal(state.items.at(-2).rows[8],'Signalétique');
 host.querySelector(`[data-grid-row-remove="${last-1}"][data-grid-row="0"]`).click();
 assert.equal(state.items.at(-2).rows.length,8);
 assert.equal(state.items.at(-2).rows[7],'Signalétique');
 const oldConfirm=globalThis.confirm;globalThis.confirm=()=>true;
 host.querySelector(`[data-grid-example="${last-1}"]`).click();globalThis.confirm=oldConfirm;
 assert.equal(state.items.at(-2).label,'Que penses-tu de :');
 assert.equal(state.items.at(-2).rows[0],'La DATE de l’évènement');
 kind=host.querySelector(`[data-index="${last-1}"][data-prop="kind"]`);kind.value='rating10';kind.dispatchEvent(new dom.window.Event('input'));kind.dispatchEvent(new dom.window.Event('change'));
 assert.equal(state.items.at(-2).kind,'rating10');
 assert.equal(state.items.at(-2).rows,undefined);
 const rows=[{id:'1',type:'visiteur',created_at:'2026-10-04T00:00:00Z',answers:{community:'Basket',satisfaction:5,highlights:'Bonne ambiance'}},{id:'2',type:'visiteur',created_at:'2026-10-04T00:00:00Z',answers:{community:'TCG',satisfaction:1,improvements:'Trop de monde'}}];
 assert.match(surveyResultsMarkup(rows,'all',2026,{community:'Basket'}),/Vue Basket · 1 réponses/);
 assert.doesNotMatch(surveyResultsMarkup(rows,'all',2026,{community:'Basket'}),/Trop de monde/);
 const unit=surveyResultsMarkup(rows,'responses',2026,{community:'Basket',ratingSort:'high',responseType:'visiteur'});
 assert.match(unit,/Trier par note du salon/);
 assert.match(unit,/Bonne ambiance/);
 assert.doesNotMatch(unit,/Trop de monde/);
 assert.doesNotMatch(surveyResultsMarkup(rows,'visiteur',2026),/<h2>Réponses individuelles<\/h2>/);
 dom.window.close();
});
const brandingSQL=await readFile(new URL('../supabase/migrations/011_edition_branding.sql',import.meta.url),'utf8');
const yearLinksSQL=await readFile(new URL('../supabase/migrations/012_survey_year_links.sql',import.meta.url),'utf8');
const gridSQL=await readFile(new URL('../supabase/migrations/013_survey_grid_rating10.sql',import.meta.url),'utf8');
test('grille et note 0–10 : édition, réponse anonyme et export lisible',async()=>{const db=await setup();try{
 await db.exec('alter table crm_editions add column closed_at timestamptz');
 await db.exec(editorMigration);await db.exec(gridSQL);await db.exec('set role authenticated');
 const schema=[{key:'experience',label:'Ton expérience',kind:'grid',rows:['Accueil','Signalétique'],columns:['Bien','Moyen','À améliorer'],required:true},{key:'score',label:'Ta note',kind:'rating10',required:true}];
 await db.query("select crm_survey_save_form($1,2026,'visiteur',0,$2)",[wid,schema]);
 await assert.rejects(db.query("select crm_survey_save_form($1,2026,'vip',0,$2)",[wid,[{...schema[0],rows:['Accueil','Accueil']}]]),e=>e.code==='22023');
 await db.exec('reset role');await db.exec('set role anon');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{experience:{Accueil:'Bien'},score:10}]),e=>e.code==='22023');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{experience:{Accueil:'Bien',Signalétique:'Moyen',Inconnue:'Bien'},score:10}]),e=>e.code==='22023');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{experience:{Accueil:'Bien',Signalétique:'Moyen'},score:11}]),e=>e.code==='22023');
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{experience:{Accueil:'Bien',Signalétique:'Moyen'},score:10}]);
 await db.exec('reset role');await db.exec('set role authenticated');
 const rows=(await db.query('select crm_survey_results($1,2026) as result',[wid])).rows[0].result;
 assert.equal(rows[0].answers.experience.Signalétique,'Moyen');
 assert.ok(buildSurveyCSV(rows).includes('Ton expérience — Accueil'));
 assert.ok(buildSurveyCSV(rows).includes('Ton expérience — Signalétique'));
 assert.ok(validateAnswers('visiteur',rows[0].answers,schema));
 assert.ok(!validateAnswers('visiteur',{experience:{Accueil:'Bien'},score:10},schema));
 }finally{await db.close()}});
test('sous-question conditionnelle : Oui la rend obligatoire, Non la saute',async()=>{const db=await setup();try{
 await db.exec('alter table crm_editions add column closed_at timestamptz');
 await db.exec(editorMigration);await db.exec(gridSQL);await db.exec('set role authenticated');
 const schema=[{key:'bought',label:'As-tu acheté ?',kind:'choice',options:['Oui','Non'],required:true},{key:'what',label:'Quoi ?',kind:'short',required:true,showIf:{key:'bought',equals:'Oui'}},{key:'score',label:'Ta note',kind:'rating10',required:true}];
 await db.query("select crm_survey_save_form($1,2026,'visiteur',0,$2)",[wid,schema]);
 await assert.rejects(db.query("select crm_survey_save_form($1,2026,'vip',0,$2)",[wid,[schema[1],schema[0]]]),e=>e.code==='22023');
 await db.exec('reset role');await db.exec('set role anon');
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{bought:'Non',score:8}]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{bought:'Oui',score:8}]),e=>e.code==='22023');
 await assert.rejects(db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{bought:'Non',what:'Cartes',score:8}]),e=>e.code==='22023');
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{bought:'Oui',what:'Cartes',score:8}]);
 }finally{await db.close()}});
test('liens millésimés : logo et réponses restent dans la bonne année',async()=>{const db=await setup();try{
 await db.exec(`alter table crm_editions add column closed_at timestamptz;
 create table crm_settings(workspace_id uuid,edition_year integer,id text,payload jsonb);
 create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(bucket_id text,name text);
 create function storage.foldername(path text) returns text[] language sql immutable as $$select string_to_array(regexp_replace(path,'/[^/]*$',''),'/')$$;
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;
 grant select on crm_editions to authenticated;
 grant insert on storage.objects to authenticated;
 insert into crm_settings values('${wid}',2026,'main','{"logoPath":"${wid}/2026/logo.png"}');`);
 await db.exec(editorMigration);await db.exec(brandingSQL);
 await db.query('insert into crm_editions(workspace_id,year) values($1,2027)',[wid]);
 await db.exec(yearLinksSQL);await db.exec('set role anon');
 const getInfo=async(year=2026)=>(await db.query('select crm_public_survey_info($1,$2) as result',['lcs',year])).rows[0].result;
 assert.equal((await getInfo()).logo,`${wid}/2026/logo.png`);
 assert.equal((await getInfo(2027)).logo,null);
 assert.equal((await db.query('select crm_public_survey_info($1,$2) as result',['lcs',null])).rows[0].result.year,2026);
 await assert.rejects(db.query('select crm_public_survey_info($1,$2)',['lcs',2025]),e=>e.code==='22023');
 const answers={community:'Basket',duration:'1 à 2 heures',purchase:'Non',satisfaction:5,returnIntent:'Oui'};
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[answers]);
 await db.query("select crm_submit_survey('lcs',2027,'visiteur',$1)",[answers]);
 await assert.rejects(db.query("select crm_submit_survey('lcs',2025,'visiteur',$1)",[answers]),e=>e.code==='22023');
 await db.exec('reset role');await db.exec('set role authenticated');
 assert.equal((await db.query('select crm_survey_results($1,2026) as rows',[wid])).rows[0].rows.length,1);
 assert.equal((await db.query('select crm_survey_results($1,2027) as rows',[wid])).rows[0].rows.length,1);
 }finally{await db.close()}});
test('logo annuel public, upload réservé aux membres de l’édition ouverte',async()=>{const db=await setup();try{
 await db.exec(`alter table crm_editions add column closed_at timestamptz;
 create table crm_settings(workspace_id uuid,edition_year integer,id text,payload jsonb);
 create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(bucket_id text,name text);
 create function storage.foldername(path text) returns text[] language sql immutable as $$select string_to_array(regexp_replace(path,'/[^/]*$',''),'/')$$;
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;
 grant select on crm_editions to authenticated;
 grant insert on storage.objects to authenticated;
 insert into crm_settings values('${wid}',2026,'main','{"logoPath":"${wid}/2026/00000000-0000-0000-0000-000000000002.png"}');`);
 await db.exec(editorMigration);await db.exec(brandingSQL);
 await db.exec('set role anon');
 const info=(await db.query("select crm_public_survey_info('lcs') as result")).rows[0].result;
 assert.equal(info.logo,`${wid}/2026/00000000-0000-0000-0000-000000000002.png`);
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[info.logo]),e=>e.code==='42501');
 await db.exec('reset role');await db.exec('set role authenticated');
 await db.query("insert into storage.objects values('lcs-branding',$1)",[info.logo]);
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[`${wid}/2027/00000000-0000-0000-0000-000000000003.png`]),e=>e.code==='42501');
 await db.exec('reset role');await db.query(`update crm_editions set closed_at=now() where workspace_id='${wid}' and year=2026`);await db.exec('set role authenticated');
 await assert.rejects(db.query("insert into storage.objects values('lcs-branding',$1)",[`${wid}/2026/00000000-0000-0000-0000-000000000004.png`]),e=>e.code==='42501');
 }finally{await db.close()}});
test('dupliquer un questionnaire vers une autre année ne copie aucune réponse',async()=>{const db=await setup();try{
 await db.exec('alter table crm_editions add column closed_at timestamptz');
 await db.exec(editorMigration);
 await db.exec('set role anon');
 await db.query("select crm_submit_survey('lcs',2026,'visiteur',$1)",[{community:'Basket',duration:'1 à 2 heures',purchase:'Oui',satisfaction:5,returnIntent:'Oui'}]);
 await db.exec('reset role');
 await db.query('insert into crm_editions(workspace_id,year) values($1,2027)',[wid]);
 await db.exec('set role authenticated');
 const schema=structuredClone(questions.visiteur);
 await db.query("select crm_survey_save_form($1,2027,'visiteur',0,$2)",[wid,schema]);
 const target=(await db.query('select crm_survey_form_admin($1,2027) as forms',[wid])).rows[0].forms;
 assert.deepEqual(target.visiteur.questions,schema);
 assert.equal((await db.query('select crm_survey_results($1,2027) as rows',[wid])).rows[0].rows.length,0);
 assert.equal((await db.query('select crm_survey_results($1,2026) as rows',[wid])).rows[0].rows.length,1);
 }finally{await db.close()}});
