import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import * as XLSX from 'xlsx';
import {startCRM} from '../src/crm.js';
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
const tick=()=>new Promise(r=>setTimeout(r,15));
async function setup(path,extra={}){const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/'+path+'?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});const api=startCRM(null,{year:2026,role:'admin',userId:a,members:[{member_id:a,first_name:'Alex',member_role:'admin'},{member_id:b,first_name:'Camille',member_role:'editor'}],save:()=>{},...extra});await tick();return {dom,api}}
test('mur : onglets et compteurs, cascade, mentions, clôture et suppression',async()=>{
 let data={messages:[{id:'post',author_id:a,author_name:'Alex',body:'Salut',created_at:'2026-10-09T08:00:00Z',topic_id:'topic',attachments:[]}],topics:[{id:'topic',name:'Exposants'}],seen_at:null};const actions=[];
 const {dom,api}=await setup('mur-echange',{wallRequest:async(action,v)=>{actions.push({action,v});if(action==='read')return structuredClone(data);if(action==='close')data.messages.find(m=>m.id===v.id).closed_at=new Date().toISOString();if(action==='delete')data.messages=data.messages.filter(m=>m.id!==v.id);return {}}});
 const state=api.getState();state.tasks=[{id:'t1',title:'Préparer les tables',category:'Logistique',assigneeId:a},{id:'t2',title:'Poster',category:'Communication',assigneeId:b}];state.exhibitors=[{id:'e1',first:'Jean',last:'Dupont',community:'Basket'},{id:'e2',first:'Sam',last:'Doe',community:'TCG'}];api.replaceState(state);assert.match(document.querySelector('[data-wall-topic="topic"]').textContent,/Exposants \(1\)/);
 const f=document.getElementById('wallPublish'),change=s=>s.dispatchEvent(new Event('change',{bubbles:true}));let group=f.querySelector('[data-wall-group]');group.value='record';change(group);const kind=f.querySelector('[data-wall-kind]');kind.value='exhibitors';change(kind);const filter=f.querySelector('[data-wall-category]');filter.value='Basket';change(filter);assert.equal(f.elements.linked.options.length,2);assert.equal(f.elements.linked.options[1].value,'exhibitors:e1');f.elements.body.value='Bonjour ';const mention=f.querySelector('[data-wall-mention]');mention.value='@[Camille]';change(mention);assert.match(f.elements.body.value,/@\[Camille\]/);document.querySelector('[data-wall-topic="topic"]').click();assert.match(document.getElementById('wallPublish').elements.body.value,/@\[Camille\]/);assert.equal(document.getElementById('wallPublish').elements.linked.options.length,2);
 document.querySelector('[data-wall-action="close"]').click();await tick();assert.equal(document.querySelector('.wallReply'),null);assert.match(document.querySelector('.wall-post').textContent,/Clôturé/);document.querySelector('[data-wall-action="delete"]').click();await tick();assert.equal(document.querySelector('.wall-post'),null);assert.ok(actions.some(x=>x.action==='delete'));dom.window.close();
});
test('Suivi déplacé dans Mes tâches et pins limités au compte connecté',async()=>{
 const {dom,api}=await setup('vue-ensemble');const state=api.getState();state.tasks=[{id:'mine',title:'Ma tâche',assigneeId:a,status:'À faire'},{id:'other',title:'Tâche autre compte',assigneeId:b,status:'À faire'}];api.replaceState(state);assert.equal(document.querySelector('.notification-center'),null);assert.equal(document.querySelector('#nav [data-view="mytasks"] .notification-pin').textContent,'1');document.querySelector('[data-view="mytasks"]').click();assert.ok(document.querySelector('.notification-center'));assert.doesNotMatch(document.querySelector('.notification-center').textContent,/Tâche autre compte/);assert.equal(document.querySelectorAll('tbody tr').length,1);dom.window.close();
});
test('page VIP : aperçu, import, filtres et édition manuelle des cinq champs',async()=>{
 let rows=[];const requests=[];const {dom}=await setup('vip',{vipRequest:async(action,v)=>{requests.push({action,v});if(action==='read')return structuredClone(rows);if(action==='import'){rows=v.records.map((r,i)=>({...r,id:'p'+i,version:1}));return {added:rows.length,updated:0}}if(action==='save'){rows=v.records.map(r=>({...r,version:(r.version||0)+1}));return {}}return {}}});
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Nom participant','Prénom participant','Email payeur','Es-tu déjà venu au Lille Card Show ?','Quelles cartes vas-tu chercher en priorité sur le salon ?','Numéro de billet'],['Dupont','Jean','payeur@example.test','Oui','Basket','ticket1']]),'Liste');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),input=document.querySelector('[data-vip-file]');Object.defineProperty(input,'files',{value:[{name:'VIP.xlsx',size:buffer.length,arrayBuffer:async()=>buffer}]});input.dispatchEvent(new Event('change',{bubbles:true}));for(let i=0;i<100&&!document.querySelector('[data-vip-confirm]');i++)await tick();assert.equal(rows.length,0);assert.match(document.querySelector('.vip-import').textContent,/1 participants/);document.querySelector('[data-vip-confirm]').click();await tick();assert.equal(rows.length,1);assert.equal(requests.find(x=>x.action==='import').v.records[0].email,'payeur@example.test');document.querySelector('[data-vip-edit]').click();let f=document.getElementById('vipEditForm');f.elements.priority.value='TCG';f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(rows[0].priority,'TCG');const filter=document.querySelector('[data-vip-kind]');filter.value='Early Access';filter.dispatchEvent(new Event('change',{bubbles:true}));assert.equal(document.querySelector('[data-vip-edit]'),null);dom.window.close();
});
