import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {JSDOM} from 'jsdom';
import {startCRM} from '../src/crm.js';
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',v='00000000-0000-0000-0000-000000000003',w='10000000-0000-0000-0000-000000000001';
test('mur SQL: droits, liens, fichiers privés, auteurs, notifications, isolation, clôture',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table crm_workspaces(id uuid primary key);create table crm_members(workspace_id uuid,user_id uuid,role text,first_name text);create table crm_editions(workspace_id uuid,year integer,closed_at timestamptz,primary key(workspace_id,year));create table crm_v2_status(workspace_id uuid);create table crm_tasks(workspace_id uuid,edition_year integer,id text);create table crm_exhibitors(like crm_tasks);create table crm_partners(like crm_tasks);create table storage.objects(bucket_id text,name text,owner_id text);create function crm_has_role(w text,roles text[]) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.crm_members where workspace_id::text=w and user_id=auth.uid() and role=any(roles))$$;insert into auth.users values('${a}'),('${b}'),('${v}');insert into crm_workspaces values('${w}');insert into crm_members values('${w}','${a}','admin','Alex'),('${w}','${b}','editor','Camille'),('${w}','${v}','viewer','Samir');insert into crm_editions values('${w}',2026,null),('${w}',2027,null);insert into crm_v2_status values('${w}');insert into crm_tasks values('${w}',2026,'t1');insert into storage.objects values('lcs-private','${w}/blob1','${a}');`);
 await db.exec(await readFile(new URL('../supabase/migrations/018_team_wall.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/019_wall_topics_vip.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/migrations/019_wall_topics_vip.sql',import.meta.url),'utf8'));
 const user=async id=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated;`);
 const call=async(action,values={},year=2026,workspace=w)=>(await db.query('select crm_wall($1,$2,$3,$4) as d',[workspace,year,action,JSON.stringify(values)])).rows[0].d;
 await user(a);const post={id:crypto.randomUUID(),body:'Devis reçu',linked_kind:'tasks',linked_id:'t1',attachments:[{blobId:'blob1',fileName:'devis.pdf',size:10}]};await call('publish',post);await call('publish',post);let feed=await call('read');assert.equal(feed.messages.length,1);assert.equal(feed.messages[0].author_name,'Alex');assert.equal(feed.messages[0].author_id,a);
 await assert.rejects(db.query('select * from crm_wall_messages'),e=>e.code==='42501');await assert.rejects(call('publish',{id:crypto.randomUUID(),body:'x',linked_kind:'tasks',linked_id:'missing'}),/introuvable/);
 await user(b);await assert.rejects(call('publish',{...post,id:crypto.randomUUID()}),/autorisée/);const reply={id:crypto.randomUUID(),body:'Merci',parent_id:post.id};await call('publish',reply);await assert.rejects(call('publish',{...reply,id:crypto.randomUUID()},2027),/clôturée|supprimée/);
 await user(a);feed=await call('read');assert.equal(feed.messages[1].author_name,'Camille');assert.equal(feed.seen_at,null);await call('seen',{through:feed.messages[0].created_at});assert.ok((await call('read')).messages[1].created_at>(await call('read')).seen_at);await call('seen',{through:feed.messages[1].created_at});assert.ok((await call('read')).seen_at);assert.equal((await call('read',{},2027)).messages.length,0);await assert.rejects(call('read',{},2026,'20000000-0000-0000-0000-000000000001'),e=>e.code==='42501');

 await call('topic_save',{name:'Exposants'});const topic=(await call('read')).topics[0];await call('topic_save',{id:topic.id,name:'Exposants / partenaires'});const mentioned={id:crypto.randomUUID(),body:'Bonjour @[Camille]',topic_id:topic.id};await call('publish',mentioned);assert.deepEqual((await call('read')).messages.find(m=>m.id===mentioned.id).mentions,[b]);
 const everyone={id:crypto.randomUUID(),body:'@tout le monde — point équipe'};await call('publish',everyone);assert.deepEqual((await call('read')).messages.find(m=>m.id===everyone.id).mentions,['all']);
 await user(b);await assert.rejects(call('delete',{id:mentioned.id}),e=>e.code==='42501');await assert.rejects(call('close',{id:mentioned.id}),e=>e.code==='42501');await call('close',{id:reply.id});assert.ok((await call('read')).messages.find(m=>m.id===reply.id).closed_at);
 await user(a);await call('close',{id:post.id});await assert.rejects(call('publish',{id:crypto.randomUUID(),parent_id:post.id,body:'interdit'}),/clôturée/);await call('reopen',{id:post.id});await call('topic_delete',{id:topic.id});assert.equal((await call('read')).messages.find(m=>m.id===mentioned.id).topic_id,null);assert.equal((await call('read')).topics.length,0);await call('delete',{id:mentioned.id});assert.equal((await call('read')).messages.find(m=>m.id===mentioned.id),undefined);await call('delete',{id:everyone.id});
 const vip=async(action,values={},year=2026)=>(await db.query('select crm_vip($1,$2,$3,$4) as d',[w,year,action,JSON.stringify(values)])).rows[0].d;
 const participant={sourceKey:'ticket1',kind:'VIP',last:'Dupont',first:'Jean',email:'payeur@example.test',returning:'Oui',priority:'Basket'};assert.deepEqual(await vip('import',{records:[participant]}),{added:1,updated:0});assert.deepEqual(await vip('import',{records:[{...participant,priority:'TCG'}]}),{added:0,updated:1});let vipRows=await vip('read');assert.equal(vipRows.length,1);assert.equal(vipRows[0].priority,'TCG');assert.equal((await vip('read',{},2027)).length,0);await vip('save',{records:[{...vipRows[0],first:'Jacques'}]});await assert.rejects(vip('save',{records:[vipRows[0]]}),e=>e.code==='40001');await assert.rejects(vip('import',{records:[{...participant,sourceKey:'ticket2'},{...participant,sourceKey:'ticket3',kind:'wrong'}]}),/invalide/);assert.equal((await vip('read')).length,1);await assert.rejects(db.query('select * from crm_vip_participants'),e=>e.code==='42501');
 await user(v);await vip('read');await assert.rejects(vip('import',{records:[participant]}),e=>e.code==='42501');await assert.rejects(call('topic_save',{name:'interdit'}),e=>e.code==='42501');await assert.rejects(db.query("select crm_wall_base($1,2026,'read','{}')",[w]),e=>e.code==='42501');
 await user(v);await call('read');await call('seen',{through:feed.messages[1].created_at});await assert.rejects(call('publish',{id:crypto.randomUUID(),body:'non'}),e=>e.code==='42501');
 await db.exec(`reset role;update crm_editions set closed_at=now() where year=2026`);await user(a);await assert.rejects(call('publish',{id:crypto.randomUUID(),body:'fermé'}),e=>e.code==='42501');assert.equal((await call('read')).messages.length,2);await assert.rejects(vip('import',{records:[participant]}),e=>e.code==='42501');
 }finally{await db.close()}
});
test('navigation, mes tâches filtrées et commentaires existants réutilisés',async()=>{
 const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/mes-taches?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});const api=startCRM(null,{role:'admin',userId:a,members:[{member_id:a,first_name:'Alex',member_role:'admin'}],save:()=>{}});const state=api.getState();state.tasks=[{id:'own',title:'Ma tâche',assigneeId:a},{id:'other',title:'Pas ma tâche',assigneeId:b},{id:'legacy',title:'Non attribuée',owner:'Alex'}];state.exhibitors=[{id:'e',first:'Jean',last:'Dupont',vendorType:'Pro',note:'Ancien commentaire complet '+'.'.repeat(100)}];state.partners=[{id:'p',company:'Partenaire',note:'Note partenaire'}];api.replaceState(state);assert.equal(document.querySelectorAll('tbody tr').length,1);assert.match(document.querySelector('tbody').textContent,/Ma tâche/);assert.ok(document.querySelector('details[data-nav-group="Tâches"]'));
 document.querySelector('[data-view="exhibitors"]').click();document.querySelector('[data-internal-comment]').click();assert.match(document.getElementById('overlay').textContent,/Ancien commentaire complet/);document.querySelector('[data-edit="exhibitors:e"]').click();assert.equal(document.getElementById('editForm').elements.note.value,state.exhibitors[0].note);document.querySelector('.close').click();document.querySelector('[data-view="partners"]').click();assert.match(document.querySelector('thead').textContent,/Commentaires/);assert.match(document.querySelector('[data-internal-comment]').textContent,/Note partenaire/);document.querySelector('[data-view="tasks"]').click();assert.equal(document.querySelector('[data-tab="tasks:list"]'),null);dom.window.close();
});
test('publication, pièce jointe, réponse et badge sans exposer HTML ni email',async()=>{
 const dom=new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://crm.test/mur-echange?year=2026'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,FormData:dom.window.FormData,Event:dom.window.Event,scrollTo:()=>{},alert:()=>{},confirm:()=>true});let feed={messages:[],seen_at:null},uploaded=[];const backend={role:'admin',userId:a,members:[{member_id:a,first_name:'Alex',member_role:'admin'}],save:()=>{},putBlob:async(id,file)=>uploaded.push({id,file}),wallRequest:async(action,values)=>{if(action==='read')return structuredClone(feed);if(action==='seen'){feed.seen_at=values.through;return {}}feed.messages.push({...values,author_id:a,author_name:'Alex',created_at:new Date().toISOString()});return {id:values.id}}};const api=startCRM(null,backend);await new Promise(r=>setTimeout(r,0));const form=document.getElementById('wallPublish');form.elements.body.value='<script>alerte</script>';Object.defineProperty(form.elements.files,'files',{value:[new dom.window.File(['devis'],'devis.pdf',{type:'application/pdf'})]});form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.equal(uploaded.length,1);assert.equal(feed.messages[0].attachments[0].fileName,'devis.pdf');assert.equal(document.querySelector('.wall-post script'),null);assert.match(document.querySelector('.wall-post').textContent,/<script>alerte<\/script>/);assert.ok(document.querySelector('[data-wall-file]'));
 const reply=document.querySelector('.wallReply');reply.elements.body.value='Bien reçu';reply.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,10));assert.equal(feed.messages[1].parent_id,feed.messages[0].id);assert.match(document.querySelector('.wall-reply').textContent,/Alex/);feed.messages.push({id:crypto.randomUUID(),parent_id:feed.messages[0].id,body:'Nouvelle réponse',author_id:b,author_name:'Camille',created_at:new Date(Date.now()+100).toISOString(),attachments:[]});await api.refreshWall();assert.match(document.querySelector('#nav [data-view="wall"]').textContent,/1/);document.querySelector('[data-wall-seen]').click();await new Promise(r=>setTimeout(r,10));assert.equal(document.querySelector('[data-wall-seen]'),null);api.setClosed(true);assert.equal(document.getElementById('wallPublish'),null);assert.equal(document.querySelector('.wallReply'),null);dom.window.close();
});
