import {createClient} from '@supabase/supabase-js';
import {questions,activeQuestions,validateAnswers} from './survey-schema.js';
import './survey.css';
const type=document.body.dataset.survey,root=document.getElementById('surveyRoot');
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const client=url&&key?createClient(url,key):null;
let edition=null,step=0,busy=false;
const answers={};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const label={visiteur:'Visiteur',vip:'VIP & Early Access',exposant:'Exposant & partenaire'}[type];
function render(){
 const list=activeQuestions(type,answers),q=list[step];
 if(!q)return;
 const widget=q.kind==='rating'?`<div class="rating" role="group" aria-label="Note de 0 à 5">${Array.from({length:6},(_,n)=>`<button type="button" data-value="${n}" class="${answers[q.key]===n?'selected':''}" aria-pressed="${answers[q.key]===n}">${n}</button>`).join('')}</div><p class="scale-label"><span>0 · Pas satisfait·e</span><span>5 · Très satisfait·e</span></p>`:q.kind==='choice'?`<div class="choices">${q.options.map((option,i)=>`<button type="button" data-value="${escape(option)}" class="${answers[q.key]===option?'selected':''}" aria-pressed="${answers[q.key]===option}"><span>${i+1}</span>${escape(option)}</button>`).join('')}</div>`:`<textarea id="answer" maxlength="1200" rows="5" placeholder="Ta réponse…">${escape(answers[q.key]||'')}</textarea>`;
 root.innerHTML=`<div class="survey-shell"><header><div class="logo">LCS</div><div><strong>Lille Card Show</strong><small>Ton avis · ${escape(label)}</small></div></header><div class="progress" role="progressbar" aria-valuenow="${step+1}" aria-valuemin="1" aria-valuemax="${list.length}"><i style="width:${(step+1)/list.length*100}%"></i></div><div class="step-counter">Question ${step+1} sur ${list.length}</div><section class="question"><h1>${escape(q.label)}</h1><p>${escape(q.hint||'Une réponse spontanée nous aide à améliorer la prochaine édition.')}</p>${widget}${q.required?'':`<small>Facultatif · tu peux passer cette question</small>`}</section><footer><button type="button" id="previous" ${step===0?'disabled':''}>← Retour</button><button type="button" id="next" class="primary" ${busy?'disabled':''}>${step===list.length-1?'Envoyer mon avis':'Continuer →'}</button></footer><p class="privacy">Aucun compte nécessaire. Aucun nom demandé${type==='exposant'?', sauf si tu souhaites en laisser un à la fin':''}.</p><p id="error" role="alert"></p></div>`;
 root.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{answers[q.key]=q.kind==='rating'?Number(b.dataset.value):b.dataset.value;render()});
 root.querySelector('#previous').onclick=()=>{if(q.kind==='text')answers[q.key]=root.querySelector('#answer').value.trim();step=Math.max(0,step-1);render()};
 root.querySelector('#next').onclick=async()=>{if(q.kind==='text')answers[q.key]=root.querySelector('#answer').value.trim();if(q.required&&(answers[q.key]===undefined||answers[q.key]==='')){root.querySelector('#error').textContent='Choisis une réponse pour continuer.';return}if(step<activeQuestions(type,answers).length-1){step++;render();return}if(!validateAnswers(type,answers)){root.querySelector('#error').textContent='Vérifie les réponses avant de continuer.';return}busy=true;root.querySelector('#next').disabled=true;const {error}=await client.rpc('crm_submit_survey',{p_code:'lcs',p_year:edition,p_type:type,p_answers:answers});busy=false;if(error){root.querySelector('#next').disabled=false;root.querySelector('#error').textContent='Envoi impossible. Réessaie dans quelques instants.';return}root.innerHTML=`<div class="survey-shell done"><div class="logo">LCS</div><h1>Merci pour ton avis !</h1><p>Ton retour nous aide à améliorer la prochaine édition du Lille Card Show.</p></div>`};
}
async function boot(){if(!client)throw Error('Configuration manquante');const {data,error}=await client.rpc('crm_public_survey_info',{p_code:'lcs'});if(error||!data?.year)throw Error('Formulaire indisponible pour le moment.');edition=data.year;render()}
boot().catch(err=>root.innerHTML=`<div class="survey-shell"><h1>Formulaire indisponible</h1><p>${escape(err.message)}</p></div>`);
