import {questions} from './survey-schema.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={rating:'Note de 0 à 5',choice:'Choix unique',checkbox:'Cases à cocher',dropdown:'Liste déroulante',text:'Texte long',short:'Réponse courte',number:'Nombre',date:'Date'};
export function createEditor(type,config){return {type,version:config?.version||0,items:structuredClone(config?.questions||questions[type])};}
export function renderSurveyEditor(root,state,{onSave,onClose}){
 const render=()=>{
  root.innerHTML=`<section class="panel survey-editor"><div class="panel-head"><div><h2>Modifier le formulaire ${escape({visiteur:'Visiteur',vip:'VIP / Early Access',exposant:'Exposant / partenaire'}[state.type])}</h2><p class="sub">Glisse les questions pour choisir leur ordre. Les réponses déjà reçues conservent leurs intitulés.</p></div></div><ol class="survey-editor-list">${state.items.map((q,i)=>`<li draggable="true" data-question-index="${i}"><div class="survey-editor-head"><span class="survey-grip" title="Glisser pour déplacer" aria-hidden="true">⠿</span><strong>Question ${i+1}</strong><div class="actions"><button type="button" class="btn small" data-survey-up="${i}" aria-label="Monter la question ${i+1}" ${i===0?'disabled':''}>↑</button><button type="button" class="btn small" data-survey-down="${i}" aria-label="Descendre la question ${i+1}" ${i===state.items.length-1?'disabled':''}>↓</button><button type="button" class="btn small danger" data-survey-remove="${i}" aria-label="Supprimer la question ${i+1}">Supprimer</button></div></div><div class="survey-editor-fields"><label>Question<input data-index="${i}" data-prop="label" value="${escape(q.label)}" maxlength="200"></label><label>Type<select data-index="${i}" data-prop="kind">${Object.entries(kinds).map(([key,name])=>`<option value="${key}" ${q.kind===key?'selected':''}>${name}</option>`).join('')}</select></label><label class="survey-wide">Aide facultative<input data-index="${i}" data-prop="hint" value="${escape(q.hint||'')}" maxlength="300"></label>${['choice','checkbox','dropdown'].includes(q.kind)?`<label class="survey-wide">Options (une par ligne)<textarea data-index="${i}" data-prop="options" rows="${Math.max(3,q.options?.length||3)}">${escape((q.options||[]).join('\n'))}</textarea></label>`:''}<label class="survey-required"><input type="checkbox" data-index="${i}" data-prop="required" ${q.required?'checked':''}> Réponse obligatoire</label>${q.showIf?`<p class="sub survey-wide">Affichée si « ${escape(q.showIf.key)} » = « ${escape(q.showIf.equals)} ».</p>`:''}</div></li>`).join('')}</ol><div class="survey-editor-actions"><button type="button" class="btn" data-survey-add>+ Ajouter une question</button><div class="actions"><button type="button" class="btn" data-survey-cancel>Fermer</button><button type="button" class="btn primary" data-survey-save>Publier les modifications</button></div></div><p class="sub" role="status" data-survey-message></p></section>`;
  root.querySelectorAll('[data-index]').forEach(el=>el.addEventListener('input',()=>{const q=state.items[Number(el.dataset.index)],p=el.dataset.prop;q[p]=p==='required'?el.checked:p==='options'?el.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean):el.value;}));
  root.querySelectorAll('[data-prop="kind"]').forEach(el=>el.addEventListener('change',()=>{const q=state.items[Number(el.dataset.index)];if(['choice','checkbox','dropdown'].includes(q.kind))q.options??=['Option 1','Option 2'];else delete q.options;render()}));
  root.querySelectorAll('[data-survey-remove]').forEach(el=>el.onclick=()=>{if(state.items.length===1){alert('Le formulaire doit conserver au moins une question.');return}if(!confirm('Retirer cette question du formulaire ? Les anciennes réponses resteront consultables.'))return;state.items.splice(Number(el.dataset.surveyRemove),1);render()});
  for(const direction of ['up','down'])root.querySelectorAll(`[data-survey-${direction}]`).forEach(el=>el.onclick=()=>{const i=Number(el.dataset[`survey${direction[0].toUpperCase()+direction.slice(1)}`]),j=i+(direction==='up'?-1:1);[state.items[i],state.items[j]]=[state.items[j],state.items[i]];render()});
  root.querySelector('[data-survey-add]').onclick=()=>{state.items.push({key:'q_'+crypto.randomUUID().replaceAll('-',''),label:'Nouvelle question',kind:'choice',options:['Option 1','Option 2'],required:false});render();root.querySelector('.survey-editor-list li:last-child input')?.focus()};
  root.querySelector('[data-survey-cancel]').onclick=onClose;
  root.querySelector('[data-survey-save]').onclick=async()=>{const msg=root.querySelector('[data-survey-message]'),button=root.querySelector('[data-survey-save]');if(state.items.some(q=>!q.label.trim()||['choice','dropdown','checkbox'].includes(q.kind)&&!q.options?.length)){msg.textContent='Renseigne chaque question et ses options.';return}button.disabled=true;msg.textContent='Enregistrement…';try{await onSave(state);onClose()}catch(error){msg.textContent=error.message;button.disabled=false}};
  let dragged=null;root.querySelectorAll('[data-question-index]').forEach(el=>{el.ondragstart=e=>{dragged=Number(el.dataset.questionIndex);e.dataTransfer.effectAllowed='move'};el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const to=Number(el.dataset.questionIndex);if(dragged!==null&&to!==dragged){const [item]=state.items.splice(dragged,1);state.items.splice(to,0,item);render()}dragged=null};});
 };render();
}
export function exportSurveyCSV(rows,year){
 const definitions=new Map();for(const row of rows){for(const q of row.questions||questions[row.type]||[])definitions.set(row.type+':'+q.key,q.label)}
 const keys=[...new Set(rows.flatMap(row=>Object.keys(row.answers||{})))].sort();const columns=['Date','Formulaire',...keys.map(key=>{const labels=[...definitions].filter(([k])=>k.endsWith(':'+key)).map(([,label])=>label);return labels[0]||key})];
 const escapeCell=value=>{let v=Array.isArray(value)?value.join(' | '):String(value??'');if(/^[=+@\-\t\r]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'};
 const csv='\ufeff'+[columns,...rows.map(row=>[new Date(row.created_at).toLocaleString('fr-FR'),row.type,...keys.map(key=>row.answers?.[key])])].map(line=>line.map(escapeCell).join(';')).join('\r\n');
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`lcs-feedback-${year}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);
}
