import {createClient} from '@supabase/supabase-js';
import {questions,activeQuestions,validateAnswers} from './survey-schema.js';
import './survey.css';
const type=document.body.dataset.survey,root=document.getElementById('surveyRoot');
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const client=url&&key?createClient(url,key):null;
let edition=null,step=0,busy=false,definitions=questions[type],logoUrl='';
const answers={};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const label={visiteur:'Visiteur',vip:'VIP & Early Access',exposant:'Exposant & partenaire'}[type];
function render(){
 const list=activeQuestions(type,answers,definitions),q=list[step];
 if(!q)return;
 const widget=['rating','rating10'].includes(q.kind)?`<div class="rating ${q.kind==='rating10'?'rating-ten':''}" role="group" aria-label="Note de 0 à ${q.kind==='rating10'?10:5}">${Array.from({length:q.kind==='rating10'?11:6},(_,n)=>`<button type="button" data-value="${n}" class="${answers[q.key]===n?'selected':''}" aria-pressed="${answers[q.key]===n}">${n}</button>`).join('')}</div><p class="scale-label"><span>0 · Pas satisfait·e</span><span>${q.kind==='rating10'?10:5} · Très satisfait·e</span></p>`:q.kind==='grid'?`<div class="survey-grid-scroll" role="group" aria-label="${escape(q.label)}"><table class="survey-grid"><thead><tr><th scope="col">Critère</th>${q.columns.map(c=>`<th scope="col">${escape(c)}</th>`).join('')}</tr></thead><tbody>${q.rows.map((row,i)=>`<tr><th scope="row">${escape(row)}</th>${q.columns.map((column,j)=>`<td><label><input type="radio" name="grid-${i}" data-grid-row="${i}" value="${escape(column)}" ${answers[q.key]?.[row]===column?'checked':''} aria-label="${escape(row)} : ${escape(column)}"></label></td>`).join('')}</tr>`).join('')}</tbody></table></div>`:q.kind==='choice'?`<div class="choices">${q.options.map((option,i)=>`<button type="button" data-value="${escape(option)}" class="${answers[q.key]===option?'selected':''}" aria-pressed="${answers[q.key]===option}"><span>${i+1}</span>${escape(option)}</button>`).join('')}</div>`:q.kind==='dropdown'?`<select id="answer"><option value="">Choisir une réponse</option>${q.options.map(option=>`<option value="${escape(option)}" ${answers[q.key]===option?'selected':''}>${escape(option)}</option>`).join('')}</select>`:q.kind==='checkbox'?`<div class="choices">${q.options.map(option=>`<label class="survey-check"><input type="checkbox" value="${escape(option)}" ${(answers[q.key]||[]).includes(option)?'checked':''}>${escape(option)}</label>`).join('')}</div>`:q.kind==='date'?`<input id="answer" type="date" value="${escape(answers[q.key]||'')}">`:q.kind==='number'?`<input id="answer" type="number" step="any" value="${escape(answers[q.key]??'')}">`:q.kind==='short'?`<input id="answer" type="text" maxlength="1200" value="${escape(answers[q.key]||'')}" placeholder="Ta réponse…">`:`<textarea id="answer" maxlength="1200" rows="5" placeholder="Ta réponse…">${escape(answers[q.key]||'')}</textarea>`;
 root.innerHTML=`<div class="survey-shell"><header>${logoUrl?`<img class="survey-year-logo" src="${escape(logoUrl)}" alt="Lille Card Show ${edition}">`:'<div class="logo">LCS</div>'}<div><strong>Lille Card Show</strong><small>Édition ${edition} · Ton avis ${escape(label)}</small></div></header><div class="progress" role="progressbar" aria-valuenow="${step+1}" aria-valuemin="1" aria-valuemax="${list.length}"><i style="width:${(step+1)/list.length*100}%"></i></div><div class="step-counter">Question ${step+1} sur ${list.length}</div><section class="question"><h1>${escape(q.label)}</h1><p>${escape(q.hint||'Une réponse spontanée nous aide à améliorer la prochaine édition.')}</p>${widget}${q.required?'':`<small>Facultatif · tu peux passer cette question</small>`}</section><footer><button type="button" id="previous" ${step===0?'disabled':''}>← Retour</button><button type="button" id="next" class="primary" ${busy?'disabled':''}>${step===list.length-1?'Envoyer mon avis':'Continuer →'}</button></footer><p class="privacy">Aucun compte nécessaire. Aucun nom demandé${type==='exposant'?', sauf si tu souhaites en laisser un à la fin':''}.</p><p id="error" role="alert"></p></div>`;
 root.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{answers[q.key]=['rating','rating10'].includes(q.kind)?Number(b.dataset.value):b.dataset.value;for(const key of Object.keys(answers))if(!activeQuestions(type,answers,definitions).some(item=>item.key===key))delete answers[key];render()});
 const capture=()=>{if(q.kind==='grid')answers[q.key]=Object.fromEntries([...root.querySelectorAll('[data-grid-row]:checked')].map(input=>[q.rows[Number(input.dataset.gridRow)],input.value]));else if(q.kind==='checkbox')answers[q.key]=[...root.querySelectorAll('.survey-check input:checked')].map(x=>x.value);else if(q.kind==='number'){const value=root.querySelector('#answer').value;answers[q.key]=value===''?'':Number(value)}else if(['text','short','date','dropdown'].includes(q.kind))answers[q.key]=root.querySelector('#answer').value.trim()};
 root.querySelector('#previous').onclick=()=>{capture();step=Math.max(0,step-1);render()};
 root.querySelector('#next').onclick=async()=>{capture();if(q.required&&(answers[q.key]===undefined||answers[q.key]===''||Array.isArray(answers[q.key])&&!answers[q.key].length||q.kind==='grid'&&!q.rows.every(row=>answers[q.key]?.[row]))){root.querySelector('#error').textContent='Choisis une réponse pour continuer.';return}if(step<activeQuestions(type,answers,definitions).length-1){step++;render();return}if(!validateAnswers(type,answers,definitions)){root.querySelector('#error').textContent='Vérifie les réponses avant de continuer.';return}busy=true;root.querySelector('#next').disabled=true;const {error}=await client.rpc('crm_submit_survey',{p_code:'lcs',p_year:edition,p_type:type,p_answers:answers});busy=false;if(error){root.querySelector('#next').disabled=false;root.querySelector('#error').textContent=error.code==='PGRST202'?'Mise à jour de la base nécessaire : préviens les organisateurs.':`Envoi impossible : ${error.message}`;return}root.innerHTML=`<div class="survey-shell done"><div class="logo">LCS</div><h1>Merci pour ton avis !</h1><p>Ton retour nous aide à améliorer la prochaine édition du Lille Card Show.</p></div>`};
}
async function boot(){if(!client)throw Error('Configuration manquante');const param=new URLSearchParams(location.search).get('year');if(param&&!/^[0-9]{4}$/.test(param))throw Error('Année invalide dans le lien.');const {data,error}=await client.rpc('crm_public_survey_info',{p_code:'lcs',p_year:param?Number(param):null});if(error||!data?.year)throw Error('Formulaire indisponible pour le moment.');edition=data.year;definitions=data.forms?.[type]?.questions||questions[type];logoUrl=data.logo?client.storage.from('lcs-branding').getPublicUrl(data.logo).data.publicUrl:edition===2026?'/logos/lcs-2026.png':'';render()}
boot().catch(err=>root.innerHTML=`<div class="survey-shell"><h1>Formulaire indisponible</h1><p>${escape(err.message)}</p></div>`);
