const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export const vipFields=[['last','Nom participant'],['first','Prénom participant'],['email','Email payeur'],['returning','Es-tu déjà venu au Lille Card Show ?'],['priority','Quelles cartes vas-tu chercher en priorité sur le salon ?']];
export async function parseVIPFile(buffer,fileName,defaultKind='VIP'){
 const XLSX=await import('xlsx');if(/\.xls$/i.test(fileName))XLSX.set_cptable(await import('xlsx/dist/cpexcel.full.mjs'));
 let input=buffer,opts={type:'array',raw:true};if(/\.csv$/i.test(fileName)){input=new TextDecoder('utf-8').decode(buffer);if(input.includes('\uFFFD'))input=new TextDecoder('windows-1252').decode(buffer);opts={type:'string',raw:true}}
 const book=XLSX.read(input,opts);let matrix,headers;
 for(const name of book.SheetNames){const rows=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:'',raw:false}),i=rows.findIndex(r=>r.some(c=>norm(c)==='nom participant')&&r.some(c=>norm(c)==='prenom participant'));if(i>=0){matrix=rows.slice(i+1);headers=rows[i].map(norm);break}}
 if(!matrix)throw Error('En-têtes Nom participant et Prénom participant introuvables.');
 const indexes=vipFields.map(([key,label])=>headers.findIndex(h=>h===norm(label)||key==='returning'&&/deja.*(venu|venue)/.test(h)||key==='priority'&&/priorite.*salon|salon.*priorite/.test(h)));
 const missing=vipFields.filter((_,i)=>indexes[i]<0);if(missing.length)throw Error('Colonnes manquantes : '+missing.map(f=>f[1]).join(', '));
 const ticket=headers.indexOf('numero de billet'),tariff=headers.indexOf('tarif'),occurrences=new Map(),records=[];
 for(const row of matrix){const record=Object.fromEntries(vipFields.map(([key],i)=>[key,String(row[indexes[i]]??'').trim()]));if(!record.last&&!record.first)continue;const rate=norm(row[tariff]);record.kind=/vip/.test(rate)?'VIP':/early/.test(rate)?'Early Access':defaultKind;const identity=JSON.stringify([record.kind,record.last,record.first,record.email]),number=String(row[ticket]??'').trim(),count=(occurrences.get(identity)||0)+1;occurrences.set(identity,count);const source=number?JSON.stringify(['ticket',number]):identity+':'+count;record.sourceKey=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(source))),x=>x.toString(16).padStart(2,'0')).join('');records.push(record)}
 if(!records.length)throw Error('Aucun participant dans ce fichier.');if(records.length>5000)throw Error('Maximum 5 000 participants par import.');return records;
}
export function createVIP({cloud,esc,onUpdate,notify}){
 let rows=[],loaded=false,loading=false,error='',query='',kind='all',preview=null,fileName='',editor=null;
 const editable=()=>cloud.role!=='viewer'&&!cloud.closed;
 const status=()=>document.querySelector('[data-vip-status]');
 async function request(action,values){if(!cloud.vipRequest)throw Error('Exécute la migration 019_wall_topics_vip.sql dans Supabase.');return cloud.vipRequest(action,values)}
 const api={async refresh(){if(loading)return;loading=true;try{const next=await request('read');const changed=JSON.stringify(rows)!==JSON.stringify(next)||!!error;rows=next;error='';loaded=true;if(changed)onUpdate()}catch(e){error=e.message;if(!loaded){loaded=true;onUpdate()}}finally{loading=false}},
 markup(){const filtered=rows.filter(r=>(kind==='all'||r.kind===kind)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));return `<div class="heading"><div><span class="eyebrow">PILOTAGE · PARTICIPANTS</span><h1>VIP</h1><p class="sub">Listes VIP et Early Access · édition ${cloud.year||2026}</p></div><div class="actions"><button class="btn" data-vip-refresh>Actualiser</button>${editable()?'<button class="btn primary" data-vip-new>+ Ajouter</button>':''}</div></div><div class="forecast-cards"><div class="stat"><span class="k">Participants</span><strong>${rows.length}</strong></div><div class="stat"><span class="k">VIP</span><strong>${rows.filter(r=>r.kind==='VIP').length}</strong></div><div class="stat"><span class="k">Early Access</span><strong>${rows.filter(r=>r.kind==='Early Access').length}</strong></div></div>${error?`<div class="panel" role="alert">${esc(error)}</div>`:''}${editable()?`<section class="panel vip-import"><h2>Importer un listing</h2><label>Fichier XLS, XLSX ou CSV<input data-vip-file type="file" accept=".xlsx,.xls,.csv"></label><p class="sub">Les colonnes sont détectées automatiquement. Le numéro de billet sert uniquement à éviter les doublons lors d’un nouvel import.</p>${preview?`<p><strong>${esc(fileName)} · ${preview.length} participants</strong></p><label>Catégorie de l’import<select data-vip-import-kind><option value="auto">Détecter depuis le tarif / fichier</option><option value="VIP">VIP</option><option value="Early Access">Early Access</option></select></label><div class="table-wrap">${table(preview.slice(0,5),false)}</div><p class="sub">Aperçu des 5 premières lignes. Un nouvel import du même billet met à jour sa fiche.</p><button class="btn primary" data-vip-confirm>Importer ${preview.length} participants</button><button class="linkbtn" data-vip-cancel>Fermer l’aperçu</button>`:''}<p class="sub" data-vip-status role="status"></p></section>`:''}${editor!==null&&editable()?editMarkup():''}<div class="toolbar"><input class="search" data-vip-search value="${esc(query)}" placeholder="Rechercher un participant…" aria-label="Rechercher un participant"><select data-vip-kind aria-label="Filtrer par catégorie"><option value="all">Tous</option>${['VIP','Early Access'].map(k=>`<option value="${k}" ${kind===k?'selected':''}>${k}</option>`).join('')}</select></div><section class="panel table-wrap">${filtered.length?table(filtered,true):`<p class="empty">${loaded?'Aucun participant dans cette vue.':'Chargement…'}</p>`}</section>`},
 mount(){if(!loaded)this.refresh();document.querySelector('[data-vip-refresh]')?.addEventListener('click',()=>this.refresh());document.querySelector('[data-vip-new]')?.addEventListener('click',()=>{editor={};onUpdate(true)});document.querySelector('[data-vip-kind]').onchange=e=>{kind=e.target.value;onUpdate(true)};document.querySelector('[data-vip-search]').oninput=e=>{query=e.target.value;onUpdate(true);const n=document.querySelector('[data-vip-search]');n.focus();n.setSelectionRange(query.length,query.length)};document.querySelector('[data-vip-file]')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>20*1024*1024){status().textContent='Maximum 20 Mo par listing.';return}e.target.disabled=true;status().textContent='Lecture du fichier…';try{const records=await parseVIPFile(await f.arrayBuffer(),f.name,/early/i.test(f.name)?'Early Access':'VIP');fileName=f.name;preview=records;onUpdate(true)}catch(err){status().textContent=err.message;e.target.disabled=false}});
 document.querySelector('[data-vip-confirm]')?.addEventListener('click',async e=>{if(!editable()||!preview)return;e.target.disabled=true;const choice=document.querySelector('[data-vip-import-kind]').value;try{const records=choice==='auto'?preview:preview.map(r=>({...r,kind:choice}));const result=await request('import',{records});preview=null;rows=await request('read');onUpdate(true);notify(`${result.added} ajouté(s), ${result.updated} mis à jour`)}catch(err){status().textContent=err.message;e.target.disabled=false}});document.querySelector('[data-vip-cancel]')?.addEventListener('click',()=>{preview=null;onUpdate(true)});
 document.querySelectorAll('[data-vip-edit]').forEach(b=>b.onclick=()=>{editor={...rows.find(r=>r.id===b.dataset.vipEdit)};onUpdate(true)});document.querySelector('[data-vip-edit-close]')?.addEventListener('click',()=>{editor=null;onUpdate(true)});
 document.querySelectorAll('[data-vip-delete]').forEach(b=>b.onclick=async()=>{if(!editable()||!confirm('Supprimer ce participant ?'))return;b.disabled=true;try{const row=rows.find(r=>r.id===b.dataset.vipDelete);await request('delete',{id:row.id,version:row.version});rows=await request('read');onUpdate(true)}catch(e){notify(e.message);b.disabled=false}});
 const form=document.getElementById('vipEditForm');if(form){form.oninput=form.onchange=e=>{if(e.target.name)editor[e.target.name]=e.target.value};}if(form)form.onsubmit=async e=>{e.preventDefault();if(!editable())return;const record={...editor,...Object.fromEntries(new FormData(form))},button=form.querySelector('[type=submit]');button.disabled=true;try{await request('save',{records:[record]});editor=null;rows=await request('read');onUpdate(true)}catch(err){form.querySelector('[data-vip-edit-status]').textContent=err.message;button.disabled=false}}
 }};
 function table(items,actions){return `<table class="data"><thead><tr><th>Catégorie</th>${vipFields.map(([k,label])=>`<th>${esc(label)}</th>`).join('')}${actions&&editable()?'<th>Actions</th>':''}</tr></thead><tbody>${items.map(r=>`<tr><td><span class="pill">${esc(r.kind)}</span></td>${vipFields.map(([k])=>`<td class="vip-${k}">${esc(r[k]||'—')}</td>`).join('')}${actions&&editable()?`<td><button class="linkbtn" data-vip-edit="${esc(r.id)}">Modifier</button><button class="linkbtn danger" data-vip-delete="${esc(r.id)}">Supprimer</button></td>`:''}</tr>`).join('')}</tbody></table>`}
 function editMarkup(){return `<section class="panel"><div class="panel-head"><h2>${editor.id?'Modifier le participant':'Nouveau participant'}</h2><button class="linkbtn" data-vip-edit-close aria-label="Fermer">×</button></div><form id="vipEditForm"><div class="form-grid"><label>Catégorie<select name="kind">${['VIP','Early Access'].map(k=>`<option value="${k}" ${editor.kind===k?'selected':''}>${k}</option>`).join('')}</select></label>${vipFields.map(([key,label])=>`<label>${esc(label)}${key==='priority'?`<textarea name="${key}" maxlength="5000">${esc(editor[key]||'')}</textarea>`:`<input name="${key}" type="${key==='email'?'email':'text'}" ${key==='last'?'required':''} value="${esc(editor[key]||'')}" maxlength="${key==='email'?320:key==='returning'?1000:150}">`}</label>`).join('')}</div><button class="btn primary" type="submit">Enregistrer</button><p data-vip-edit-status role="status"></p></form></section>`}
 return api;
}
