const normalize=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
export function vipStatistics(rows,kind){
 const group=rows.filter(r=>r.kind===kind);let yes=0,no=0;const choices=new Map();
 for(const row of group){const returning=normalize(row.returning);if(returning==='oui')yes++;else if(returning==='non')no++;const label=String(row.priority??'').trim().replace(/\s+/g,' '),key=normalize(label);if(key){const entry=choices.get(key)||{label,count:0};entry.count++;choices.set(key,entry)}}
 const answers=yes+no,communities=[...choices.values()].sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'fr')),communityAnswers=communities.reduce((n,c)=>n+c.count,0);
 return {total:group.length,yes,no,answers,missing:group.length-answers,yesPercent:answers?yes/answers*100:null,noPercent:answers?no/answers*100:null,communityAnswers,communityMissing:group.length-communityAnswers,communities:communities.map(c=>({...c,percent:c.count/communityAnswers*100}))};
}
const colors=['#FE4F14','#1303E3','#00A758','#0C9EAC','#B38B00','#c85be1','#3679da','#bd5d79','#8b7729','#677b85'];
const percent=n=>n===null?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n)+' %';
export function vipKPIs(rows,esc){
 const groups=[['VIP','VIP'],['Early Access','Early']].map(([kind,label])=>({label,stats:vipStatistics(rows,kind)}));
 return `<section class="vip-kpi-grid" aria-label="Returning et communautés">${groups.map(({label,stats:s})=>`<article class="panel vip-returning-kpi"><h2>Returning ${label}</h2><div class="vip-returning-rates"><div><span>Oui · déjà venu</span><strong class="money-positive">${percent(s.yesPercent)}</strong></div><div><span>Non · première visite</span><strong>${percent(s.noPercent)}</strong></div></div><p class="sub">${s.answers} réponse(s) Oui/Non · ${s.missing} non renseignée(s) ou autre(s)</p></article>`).join('')}${groups.map(({label,stats:s})=>{let offset=0;const stops=s.communities.map((c,i)=>{const start=offset;offset+=c.percent;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(',');return `<article class="panel vip-community-kpi"><h2>Communauté ${label}</h2>${s.communityAnswers?`<div class="vip-community-body"><div class="vip-community-pie" style="background:conic-gradient(${stops})" role="img" aria-label="${esc(s.communities.map(c=>c.label+' : '+percent(c.percent)).join(', '))}"></div><ul class="vip-community-legend">${s.communities.map((c,i)=>`<li><i style="background:${colors[i%colors.length]}" aria-hidden="true"></i><span>${esc(c.label)}</span><strong>${percent(c.percent)}</strong></li>`).join('')}</ul></div>`:'<p class="sub">Aucune réponse renseignée.</p>'}<p class="sub">${s.communityAnswers} réponse(s) renseignée(s) · ${s.communityMissing} non renseignée(s)</p></article>`}).join('')}</section>`;
}
