export function createWall({cloud,esc,getDB,onUpdate,notify}){
 let data={messages:[],seen_at:null},error='',loading=false,loaded=false;
 const editable=()=>cloud.role!=='viewer'&&!cloud.closed;
 const unread=()=>data.messages.filter(m=>m.parent_id&&m.author_id!==cloud.userId&&(!data.seen_at||m.created_at>data.seen_at)).length;
 const stamp=s=>new Date(s).toLocaleString('fr-FR');
 const author=m=>m.author_name||'Membre';
 const links=()=>['tasks','exhibitors','partners'].flatMap(kind=>(getDB()[kind]||[]).map(row=>({kind,id:row.id,label:(kind==='tasks'?'Tâche':kind==='exhibitors'?'Exposant':'Partenaire')+' · '+(row.title||row.company||[row.first,row.last].filter(Boolean).join(' ')||row.name||row.id)})));
 function item(m){return `<header><strong>${esc(author(m))}</strong><time datetime="${esc(m.created_at)}">${esc(stamp(m.created_at))}</time></header><p class="wall-text">${esc(m.body)}</p>${(m.attachments||[]).map((f,i)=>`<button type="button" class="btn small" data-wall-file="${esc(m.id)}:${i}">↓ ${esc(f.fileName)}</button>`).join('')}`}
 return {get unread(){return unread()},async refresh(){if(loading||!cloud.wallRequest)return;loading=true;try{const next=await cloud.wallRequest('read');const changed=JSON.stringify(data)!==JSON.stringify(next)||!!error;const before=unread();data=next;error='';if(loaded&&unread()>before)notify('Nouvelle réponse dans le Mur d’échange');loaded=true;if(changed)onUpdate()}catch(e){error=e.message;if(!loaded){loaded=true;onUpdate()}}finally{loading=false}},
 markup(){const related=links();return `<div class="heading"><div><span class="eyebrow">TÂCHES · ÉQUIPE</span><h1>Mur d’échange</h1><p class="sub">Discussions et documents internes · édition ${cloud.year||2026}</p></div><div class="actions"><button class="btn" data-wall-refresh>Actualiser</button>${unread()?`<button class="btn" data-wall-seen>${unread()} réponse(s) non lue(s) · Marquer comme lues</button>`:''}</div></div>${error?`<div class="panel" role="alert">${esc(error)}</div>`:''}${editable()?`<form id="wallPublish" class="panel wall-compose"><label>Message<textarea name="body" required maxlength="10000" rows="3" placeholder="Partage une information avec l’équipe…"></textarea></label><label>Relier à une fiche<select name="linked"><option value="">Aucune</option>${related.map(x=>`<option value="${esc(x.kind+':'+x.id)}">${esc(x.label)}</option>`).join('')}</select></label><label>Pièces jointes · 50 Mo maximum par fichier<input name="files" type="file" multiple></label><button class="btn primary">Publier</button><p class="sub" data-wall-status role="status"></p></form>`:'<p class="sub">Consultation uniquement.</p>'}<section class="wall-feed" aria-label="Publications de l’équipe">${data.messages.filter(m=>!m.parent_id).slice().reverse().map(m=>{const link=related.find(x=>x.kind===m.linked_kind&&x.id===m.linked_id);return `<article class="panel wall-post">${item(m)}${link?`<button class="linkbtn" data-edit="${esc(link.kind+':'+link.id)}">${esc(link.label)} →</button>`:m.linked_id?'<small>Fiche liée supprimée</small>':''}<div class="wall-replies">${data.messages.filter(r=>r.parent_id===m.id).map(r=>`<article class="wall-reply ${r.author_id!==cloud.userId&&(!data.seen_at||r.created_at>data.seen_at)?'unread':''}">${item(r)}</article>`).join('')}</div>${editable()?`<form class="wallReply" data-post="${esc(m.id)}"><label>Répondre<textarea name="body" required maxlength="10000" rows="2"></textarea></label><button class="btn small">Commenter</button><p class="sub" data-wall-status role="status"></p></form>`:''}</article>`}).join('')||`<div class="panel empty">${loaded?'Aucune publication pour le moment.':'Chargement des discussions…'}</div>`}</section>`},
 mount(){if(!loaded)this.refresh();const publish=document.getElementById('wallPublish');if(publish)publish.onsubmit=submit;document.querySelectorAll('.wallReply').forEach(f=>f.onsubmit=submit);document.querySelector('[data-wall-refresh]')?.addEventListener('click',()=>this.refresh());document.querySelector('[data-wall-seen]')?.addEventListener('click',async e=>{e.target.disabled=true;try{await cloud.wallRequest('seen',{through:data.messages.reduce((d,m)=>m.created_at>d?m.created_at:d,data.seen_at||'1970-01-01T00:00:00Z')});await this.refresh()}catch(err){notify(err.message);e.target.disabled=false}});document.querySelectorAll('[data-wall-file]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const [key,i]=b.dataset.wallFile.split(':'),file=data.messages.find(m=>m.id===key)?.attachments[Number(i)];const blob=await cloud.getBlob(file.blobId),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(err){notify(err.message)}finally{b.disabled=false}})}
 };
 async function submit(e){e.preventDefault();if(!editable())return;const form=e.target,button=form.querySelector('button'),status=form.querySelector('[data-wall-status]'),body=form.elements.body.value.trim();if(!body)return;const files=Array.from(form.elements.files?.files||[]);if(files.length>10||files.some(f=>f.size>50*1024*1024)){status.textContent='10 fichiers maximum, 50 Mo par fichier.';return}button.disabled=true;status.textContent='Envoi…';try{const attachments=[];for(const file of files){const blobId=crypto.randomUUID();await cloud.putBlob(blobId,file);attachments.push({blobId,fileName:file.name,size:file.size,mime:file.type})}const [linked_kind,linked_id]=(form.elements.linked?.value||'').split(':');await cloud.wallRequest('publish',{id:form.dataset.requestId||(form.dataset.requestId=crypto.randomUUID()),body,parent_id:form.dataset.post||null,linked_kind:linked_kind||null,linked_id:linked_id||null,attachments});form.reset();delete form.dataset.requestId;data=await cloud.wallRequest('read');error='';onUpdate(true)}catch(err){status.textContent=err.message}finally{button.disabled=false}}
}
