-- MISE À JOUR V2 : après 001_crm.sql, une seule fois.
-- Transaction intégrale : toute erreur annule la migration.
begin;
lock table public.crm_state in access exclusive mode;
create function public.crm_number(v text) returns numeric
language plpgsql immutable set search_path='' as $$
begin return v::numeric; exception when invalid_text_representation or numeric_value_out_of_range then return null; end; $$;
revoke all on function public.crm_number(text) from public;
grant execute on function public.crm_number(text) to authenticated;
create table public.crm_v2_status (
 workspace_id uuid primary key references public.crm_workspaces(id),
 revision bigint not null default 0, migrated_at timestamptz not null default now()
);
create table public.crm_history (
 id bigint generated always as identity primary key,
 workspace_id uuid not null references public.crm_workspaces(id),
 entity text not null, record_id text not null,
 before_data jsonb, after_data jsonb,
 changed_at timestamptz not null default now(), changed_by uuid references auth.users(id)
);
create table public.crm_requests (
 workspace_id uuid not null references public.crm_workspaces(id),
 request_id uuid not null, changes jsonb not null, revision bigint not null,
 created_at timestamptz not null default now(), primary key(workspace_id,request_id)
);
create table public.crm_exhibitors (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "last" text generated always as (payload->>'last') stored,
 "first" text generated always as (payload->>'first') stored,
 "company" text generated always as (payload->>'company') stored,
 "email" text generated always as (payload->>'email') stored,
 "phone" text generated always as (payload->>'phone') stored,
 "community" text generated always as (payload->>'community') stored,
 "vendorType" text generated always as (payload->>'vendorType') stored,
 "rate" text generated always as (payload->>'rate') stored,
 "amount" numeric generated always as (public.crm_number(payload->>'amount')) stored,
 "tables" numeric generated always as (public.crm_number(payload->>'tables')) stored,
 "zone" text generated always as (payload->>'zone') stored,
 "status" text generated always as (payload->>'status') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_exhibitors(workspace_id,"status");
create index on public.crm_exhibitors(workspace_id,"company");
create index on public.crm_exhibitors(workspace_id,"zone");
comment on column public.crm_exhibitors.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_contacts (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "company" text generated always as (payload->>'company') stored,
 "last" text generated always as (payload->>'last') stored,
 "first" text generated always as (payload->>'first') stored,
 "phone" text generated always as (payload->>'phone') stored,
 "email" text generated always as (payload->>'email') stored,
 "role" text generated always as (payload->>'role') stored,
 "type" text generated always as (payload->>'type') stored,
 "typeOther" text generated always as (payload->>'typeOther') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_contacts(workspace_id,"company");
comment on column public.crm_contacts.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_partners (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "company" text generated always as (payload->>'company') stored,
 "name" text generated always as (payload->>'name') stored,
 "email" text generated always as (payload->>'email') stored,
 "phone" text generated always as (payload->>'phone') stored,
 "community" text generated always as (payload->>'community') stored,
 "zone" text generated always as (payload->>'zone') stored,
 "unit" text generated always as (payload->>'unit') stored,
 "quantity" numeric generated always as (public.crm_number(payload->>'quantity')) stored,
 "amount" numeric generated always as (public.crm_number(payload->>'amount')) stored,
 "status" text generated always as (payload->>'status') stored,
 "owner" text generated always as (payload->>'owner') stored,
 "next" text generated always as (payload->>'next') stored,
 "invoiceSent" text generated always as (payload->>'invoiceSent') stored,
 "logoId" text generated always as (payload->>'logoId') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_partners(workspace_id,"status");
create index on public.crm_partners(workspace_id,"company");
create index on public.crm_partners(workspace_id,"zone");
create index on public.crm_partners(workspace_id,"owner");
comment on column public.crm_partners.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_tasks (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "category" text generated always as (payload->>'category') stored,
 "owner" text generated always as (payload->>'owner') stored,
 "status" text generated always as (payload->>'status') stored,
 "start" text generated always as (payload->>'start') stored,
 "due" text generated always as (payload->>'due') stored,
 "priority" text generated always as (payload->>'priority') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_tasks(workspace_id,"status");
create index on public.crm_tasks(workspace_id,"owner");
comment on column public.crm_tasks.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_posts (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "group" text generated always as (payload->>'group') stored,
 "channel" text generated always as (payload->>'channel') stored,
 "company" text generated always as (payload->>'company') stored,
 "contact" text generated always as (payload->>'contact') stored,
 "direct" text generated always as (payload->>'direct') stored,
 "status" text generated always as (payload->>'status') stored,
 "date" text generated always as (payload->>'date') stored,
 "publishedAt" text generated always as (payload->>'publishedAt') stored,
 "owner" text generated always as (payload->>'owner') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_posts(workspace_id,"status");
create index on public.crm_posts(workspace_id,"company");
create index on public.crm_posts(workspace_id,"owner");
comment on column public.crm_posts.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_expenses (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "category" text generated always as (payload->>'category') stored,
 "quantity" numeric generated always as (public.crm_number(payload->>'quantity')) stored,
 "estimated" numeric generated always as (public.crm_number(payload->>'estimated')) stored,
 "supplier" text generated always as (payload->>'supplier') stored,
 "status" text generated always as (payload->>'status') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_expenses(workspace_id,"status");
comment on column public.crm_expenses.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_ideas (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "author" text generated always as (payload->>'author') stored,
 "price" numeric generated always as (public.crm_number(payload->>'price')) stored,
 "link" text generated always as (payload->>'link') stored,
 "imageId" text generated always as (payload->>'imageId') stored,
 "note" text generated always as (payload->>'note') stored
);
comment on column public.crm_ideas.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_assets (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "category" text generated always as (payload->>'category') stored,
 "author" text generated always as (payload->>'author') stored,
 "blobId" text generated always as (payload->>'blobId') stored,
 "fileName" text generated always as (payload->>'fileName') stored,
 "note" text generated always as (payload->>'note') stored
);
comment on column public.crm_assets.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_invoices (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "title" text generated always as (payload->>'title') stored,
 "tag" text generated always as (payload->>'tag') stored,
 "amount" numeric generated always as (public.crm_number(payload->>'amount')) stored,
 "partnerId" text generated always as (payload->>'partnerId') stored,
 "sourceQuoteId" text generated always as (payload->>'sourceQuoteId') stored,
 "status" text generated always as (payload->>'status') stored,
 "sentDate" text generated always as (payload->>'sentDate') stored,
 "blobId" text generated always as (payload->>'blobId') stored,
 "note" text generated always as (payload->>'note') stored
);
create index on public.crm_invoices(workspace_id,"status");
create index on public.crm_invoices(workspace_id,"partnerId");
create index on public.crm_invoices(workspace_id,"sourceQuoteId");
comment on column public.crm_invoices.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_zones (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "name" text generated always as (payload->>'name') stored,
 "capacity" numeric generated always as (public.crm_number(payload->>'capacity')) stored,
 "color" text generated always as (payload->>'color') stored
);
comment on column public.crm_zones.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_settings (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "totalTables" numeric generated always as (public.crm_number(payload->>'totalTables')) stored,
 "partnerSqmPrice" numeric generated always as (public.crm_number(payload->>'partnerSqmPrice')) stored,
 "partnerTablePrice" numeric generated always as (public.crm_number(payload->>'partnerTablePrice')) stored
);
comment on column public.crm_settings.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_forecast (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id),
 "totalTables" numeric generated always as (public.crm_number(payload->>'totalTables')) stored,
 "proPrice" numeric generated always as (public.crm_number(payload->>'proPrice')) stored,
 "collectorPrice" numeric generated always as (public.crm_number(payload->>'collectorPrice')) stored,
 "partnerTablePrice" numeric generated always as (public.crm_number(payload->>'partnerTablePrice')) stored,
 "priceSqm" numeric generated always as (public.crm_number(payload->>'priceSqm')) stored,
 "hallRental" numeric generated always as (public.crm_number(payload->>'hallRental')) stored,
 "deco" numeric generated always as (public.crm_number(payload->>'deco')) stored,
 "social" numeric generated always as (public.crm_number(payload->>'social')) stored,
 "press" numeric generated always as (public.crm_number(payload->>'press')) stored
);
comment on column public.crm_forecast.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
create table public.crm_metadata (
 workspace_id uuid not null references public.crm_workspaces(id),
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,id)
);
comment on column public.crm_metadata.payload is 'Fiche complète sans perte de champs ; les colonnes métier sont des projections de lecture. Écriture via crm_apply_changes.';
alter table public.crm_exhibitors enable row level security;
revoke all on public.crm_exhibitors from anon,authenticated;
grant select on public.crm_exhibitors to authenticated;
create policy member_read on public.crm_exhibitors for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_contacts enable row level security;
revoke all on public.crm_contacts from anon,authenticated;
grant select on public.crm_contacts to authenticated;
create policy member_read on public.crm_contacts for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_partners enable row level security;
revoke all on public.crm_partners from anon,authenticated;
grant select on public.crm_partners to authenticated;
create policy member_read on public.crm_partners for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_tasks enable row level security;
revoke all on public.crm_tasks from anon,authenticated;
grant select on public.crm_tasks to authenticated;
create policy member_read on public.crm_tasks for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_posts enable row level security;
revoke all on public.crm_posts from anon,authenticated;
grant select on public.crm_posts to authenticated;
create policy member_read on public.crm_posts for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_expenses enable row level security;
revoke all on public.crm_expenses from anon,authenticated;
grant select on public.crm_expenses to authenticated;
create policy member_read on public.crm_expenses for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_ideas enable row level security;
revoke all on public.crm_ideas from anon,authenticated;
grant select on public.crm_ideas to authenticated;
create policy member_read on public.crm_ideas for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_assets enable row level security;
revoke all on public.crm_assets from anon,authenticated;
grant select on public.crm_assets to authenticated;
create policy member_read on public.crm_assets for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_invoices enable row level security;
revoke all on public.crm_invoices from anon,authenticated;
grant select on public.crm_invoices to authenticated;
create policy member_read on public.crm_invoices for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_zones enable row level security;
revoke all on public.crm_zones from anon,authenticated;
grant select on public.crm_zones to authenticated;
create policy member_read on public.crm_zones for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_settings enable row level security;
revoke all on public.crm_settings from anon,authenticated;
grant select on public.crm_settings to authenticated;
create policy member_read on public.crm_settings for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_forecast enable row level security;
revoke all on public.crm_forecast from anon,authenticated;
grant select on public.crm_forecast to authenticated;
create policy member_read on public.crm_forecast for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_metadata enable row level security;
revoke all on public.crm_metadata from anon,authenticated;
grant select on public.crm_metadata to authenticated;
create policy member_read on public.crm_metadata for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_v2_status enable row level security;
revoke all on public.crm_v2_status from anon,authenticated;
grant select on public.crm_v2_status to authenticated;
create policy member_read on public.crm_v2_status for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_history enable row level security;
revoke all on public.crm_history from anon,authenticated;
grant select on public.crm_history to authenticated;
create policy member_read on public.crm_history for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin']));
alter table public.crm_requests enable row level security;
revoke all on public.crm_requests from anon,authenticated;
-- Lecture cohérente des tables dans un seul instantané SQL.
create function public.crm_read_records(p_workspace uuid) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare result jsonb:='{}'; part jsonb; entity text; rev bigint;
begin
 if not public.crm_has_role(p_workspace::text,array['admin','editor','viewer']) then
  raise exception 'Accès refusé' using errcode='42501'; end if;
 select revision into rev from public.crm_v2_status where workspace_id=p_workspace;
 if not found then raise exception 'Migration V2 non exécutée pour cet espace'; end if;
 select payload into result from public.crm_metadata where workspace_id=p_workspace and id='main';
 result:=coalesce(result,'{}');
 foreach entity in array array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones'] loop
  execute format('select coalesce(jsonb_agg(payload order by position,id),''[]''::jsonb) from public.%I where workspace_id=$1','crm_'||entity) into part using p_workspace;
  result:=jsonb_set(result,array[entity],part);
 end loop;
 select payload into part from public.crm_settings where workspace_id=p_workspace and id='main';
 result:=jsonb_set(result,'{settings}',coalesce(part,'{}'));
 select payload into part from public.crm_forecast where workspace_id=p_workspace and id='2027';
 result:=jsonb_set(result,'{forecast2027}',coalesce(part,'{}'));
 return jsonb_build_object('revision',rev,'data',result);
end;$$;
revoke all on function public.crm_read_records(uuid) from public;
grant execute on function public.crm_read_records(uuid) to authenticated;

-- Une transaction pour toutes les fiches d'une action. Vérification par fiche.
-- Un UUID rend les réessais après coupure réseau sans effet double.
create function public.crm_apply_changes(p_workspace uuid,p_request uuid,p_changes jsonb)
returns bigint language plpgsql security definer set search_path='' as $$
declare change jsonb; entity text; key text; current_data jsonb;
 before_value jsonb; after_value jsonb; rev bigint; prior jsonb; seen text[]:='{}'; token text;
begin
 if not public.crm_has_role(p_workspace::text,array['admin','editor']) then
  raise exception 'Accès en écriture refusé' using errcode='42501'; end if;
 if p_request is null or jsonb_typeof(p_changes) is distinct from 'array' then
  raise exception 'Requête invalide' using errcode='22023'; end if;
 -- Sérialiser la courte transaction, sans comparer la révision globale.
 perform 1 from public.crm_v2_status where workspace_id=p_workspace for update;
 if not found then raise exception 'Migration V2 non exécutée'; end if;
 select changes,revision into prior,rev from public.crm_requests where workspace_id=p_workspace and request_id=p_request;
 if found then
  if prior is distinct from p_changes then raise exception 'UUID de requête réutilisé' using errcode='22023'; end if;
  return rev;
 end if;
 for change in select value from jsonb_array_elements(p_changes) loop
  entity:=change->>'entity'; key:=change->>'id';
  if entity is null or not(entity=any(array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones','settings','forecast','metadata'])) or key is null or key='' then raise exception 'Table ou identifiant invalide' using errcode='22023'; end if;
  token:=entity||':'||key;
  if token=any(seen) then raise exception 'Fiche répétée dans la requête' using errcode='22023'; end if;
  seen:=array_append(seen,token);
  if not(change ? 'before') or not(change ? 'after') then raise exception 'Version manquante' using errcode='22023'; end if;
  before_value:=nullif(change->'before','null'::jsonb);
  after_value:=nullif(change->'after','null'::jsonb);
  if after_value is not null and jsonb_typeof(after_value)<>'object' then raise exception 'Fiche invalide' using errcode='22023'; end if;
  if entity in ('settings','metadata') and key<>'main' or entity='forecast' and key<>'2027' then raise exception 'Identifiant de réglage invalide'; end if;
  if entity=any(array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones']) and after_value is not null and after_value->>'id' is distinct from key then raise exception 'Identifiant incohérent'; end if;
  if entity='metadata' and (after_value is null or after_value->>'schema' is distinct from '1') then raise exception 'Schéma CRM invalide'; end if;
  current_data:=null;
  execute format('select payload from public.%I where workspace_id=$1 and id=$2','crm_'||entity) into current_data using p_workspace,key;
  if current_data is distinct from before_value then
   raise exception 'Conflit sur % / % : recharge la fiche avant de réessayer',entity,key using errcode='40001';
  end if;
  if current_data is not distinct from after_value then continue; end if;
  insert into public.crm_history(workspace_id,entity,record_id,before_data,after_data,changed_by)
   values(p_workspace,entity,key,current_data,after_value,auth.uid());
  if after_value is null then
   execute format('delete from public.%I where workspace_id=$1 and id=$2','crm_'||entity) using p_workspace,key;
  else
   execute format('insert into public.%I(workspace_id,id,payload,updated_by) values($1,$2,$3,$4) on conflict(workspace_id,id) do update set payload=excluded.payload,version=%I.version+1,updated_at=now(),updated_by=excluded.updated_by','crm_'||entity,'crm_'||entity) using p_workspace,key,after_value,auth.uid();
  end if;
 end loop;
 update public.crm_v2_status set revision=revision+1 where workspace_id=p_workspace returning revision into rev;
 insert into public.crm_requests(workspace_id,request_id,changes,revision) values(p_workspace,p_request,p_changes,rev);
 return rev;
end;$$;
revoke all on function public.crm_apply_changes(uuid,uuid,jsonb) from public;
grant execute on function public.crm_apply_changes(uuid,uuid,jsonb) to authenticated;

-- Reprise exclusive des données DÉJÀ EN LIGNE ; aucun import local.
-- crm_state est conservée intégralement comme archive de la bascule.
do $$
declare ws record; original jsonb; entry jsonb; entity text; part jsonb; n bigint;
begin
 for ws in select w.id,s.data from public.crm_workspaces w left join public.crm_state s on s.workspace_id=w.id loop
  original:=ws.data;
  if original is null then
   original:='{"schema":1,"contactSplitVersion":1,"settings":{"score":[70,30,20],"totalTables":120,"owners":[],"accent":"#1303E3","dark":false,"partnerSqmPrice":0,"partnerTablePrice":0},"zones":[{"id":"basket","name":"Basket","capacity":30,"color":"#f96927"},{"id":"soccer","name":"Soccer","capacity":30,"color":"#22b55f"},{"id":"sports-us","name":"Sports US","capacity":30,"color":"#25b9c7"},{"id":"tcg","name":"TCG","capacity":30,"color":"#e0b726"}],"forecast2027":{"modelVersion":2,"revenueModelVersion":3}}'::jsonb;
  end if;
  if jsonb_typeof(original)<>'object' or original->>'schema' is distinct from '1' then raise exception 'Données source invalides : %',ws.id; end if;
  foreach entity in array array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones'] loop
   part:=coalesce(original->entity,'[]'::jsonb);
   if jsonb_typeof(part)<>'array' then raise exception 'Collection invalide : %',entity; end if;
   n:=0;
   for entry in select value from jsonb_array_elements(part) loop
    n:=n+1;
    if jsonb_typeof(entry)<>'object' or coalesce(entry->>'id','')='' then raise exception 'Fiche sans identifiant dans %',entity; end if;
    execute format('insert into public.%I(workspace_id,id,payload) values($1,$2,$3)','crm_'||entity) using ws.id,entry->>'id',entry;
   end loop;
   -- Comparaison exacte, y compris tous les champs non connus du code.
   execute format('select coalesce(jsonb_agg(payload order by position),''[]''::jsonb) from public.%I where workspace_id=$1','crm_'||entity) into entry using ws.id;
   if entry is distinct from part then raise exception 'Vérification de migration échouée : %',entity; end if;
  end loop;
  insert into public.crm_settings(workspace_id,id,payload) values(ws.id,'main',coalesce(original->'settings','{}'));
  insert into public.crm_forecast(workspace_id,id,payload) values(ws.id,'2027',coalesce(original->'forecast2027','{}'));
  insert into public.crm_metadata(workspace_id,id,payload) values(ws.id,'main',original-array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones','settings','forecast2027','updatedAt']);
  insert into public.crm_v2_status(workspace_id) values(ws.id);
 end loop;
end $$;
-- Restauration administrateur d'une opération, avec contrôle de conflit.
create function public.crm_restore_history(p_history bigint,p_request uuid)
returns bigint language plpgsql security definer set search_path='' as $$
declare h public.crm_history;
begin
 select * into h from public.crm_history where id=p_history;
 if not found or not public.crm_has_role(h.workspace_id::text,array['admin']) then
  raise exception 'Restauration réservée aux administrateurs' using errcode='42501'; end if;
 return public.crm_apply_changes(h.workspace_id,p_request,jsonb_build_array(jsonb_build_object(
  'entity',h.entity,'id',h.record_id,'before',h.after_data,'after',h.before_data)));
end;$$;
revoke all on function public.crm_restore_history(bigint,uuid) from public;
grant execute on function public.crm_restore_history(bigint,uuid) to authenticated;
-- Empêcher un ancien onglet V1 d'écrire après la bascule.
create or replace function public.crm_save_state(p_workspace uuid,p_expected_revision bigint,p_data jsonb)
returns bigint language plpgsql security definer set search_path='' as $$
begin raise exception 'Version du CRM obsolète : ferme cet onglet et ouvre la version V2.' using errcode='55000'; end;$$;
comment on table public.crm_state is 'Archive V1 conservée. Ne plus écrire. Données actives dans les tables métier crm_*.';
commit;
