-- Après 003_editions.sql, une seule fois. Conserve toutes les données existantes.
begin;
lock table public.crm_v2_status in access exclusive mode;
create table public.crm_ledger_entries (
 workspace_id uuid not null references public.crm_workspaces(id),
 edition_year integer not null,
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,edition_year,id),
 foreign key(workspace_id,edition_year) references public.crm_editions(workspace_id,year),
 title text generated always as (payload->>'title') stored,
 side text generated always as (payload->>'side') stored
);
alter table public.crm_ledger_entries enable row level security;
revoke all on public.crm_ledger_entries from anon,authenticated;
grant select on public.crm_ledger_entries to authenticated;
create policy member_read on public.crm_ledger_entries for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
create table public.crm_ledger_categories (
 workspace_id uuid not null references public.crm_workspaces(id),
 edition_year integer not null,
 id text not null check(length(id)>0),
 payload jsonb not null check(jsonb_typeof(payload)='object'),
 position bigint generated by default as identity,
 version bigint not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id),
 primary key(workspace_id,edition_year,id),
 foreign key(workspace_id,edition_year) references public.crm_editions(workspace_id,year),
 title text generated always as (payload->>'title') stored,
 side text generated always as (payload->>'side') stored
);
alter table public.crm_ledger_categories enable row level security;
revoke all on public.crm_ledger_categories from anon,authenticated;
grant select on public.crm_ledger_categories to authenticated;
create policy member_read on public.crm_ledger_categories for select to authenticated
using(public.crm_has_role(workspace_id::text,array['admin','editor','viewer']));
alter table public.crm_ledger_entries
 add column "categoryId" text generated always as (payload->>'categoryId') stored,
 add column "sourceId" text generated always as (payload->>'sourceId') stored,
 add column "amountCents" numeric generated always as (public.crm_number(payload->>'amountCents')) stored;
create or replace function public.crm_read_records(p_workspace uuid,p_year integer) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare result jsonb:='{}'; part jsonb; entity text; rev bigint;
begin
 if not public.crm_has_role(p_workspace::text,array['admin','editor','viewer']) then
  raise exception 'Accès refusé' using errcode='42501'; end if;
 if not exists(select 1 from public.crm_editions where workspace_id=p_workspace and year=p_year) then raise exception 'Année inexistante'; end if;
 select revision into rev from public.crm_v2_status where workspace_id=p_workspace;
 if not found then raise exception 'Migration V2 non exécutée pour cet espace'; end if;
 select payload into result from public.crm_metadata where workspace_id=p_workspace and edition_year=p_year and id='main';
 result:=coalesce(result,'{}');
 foreach entity in array array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones','ledger_entries','ledger_categories'] loop
  execute format('select coalesce(jsonb_agg(payload order by position,id),''[]''::jsonb) from public.%I where workspace_id=$1 %s','crm_'||entity,case when entity='contacts' then '' else 'and edition_year=$2' end) into part using p_workspace,p_year;
  result:=jsonb_set(result,array[entity],part);
 end loop;
 select payload into part from public.crm_settings where workspace_id=p_workspace and edition_year=p_year and id='main';
 result:=jsonb_set(result,'{settings}',coalesce(part,'{}'));
 select payload into part from public.crm_forecast where workspace_id=p_workspace and edition_year=p_year and id='2027';
 result:=jsonb_set(result,'{forecast2027}',coalesce(part,'{}'));
 return jsonb_build_object('revision',rev,'data',result);
end;$$;
revoke all on function public.crm_read_records(uuid,integer) from public;
grant execute on function public.crm_read_records(uuid,integer) to authenticated;

create or replace function public.crm_apply_changes(p_workspace uuid,p_request uuid,p_changes jsonb,p_year integer)
returns bigint language plpgsql security definer set search_path='' as $$
declare change jsonb; entity text; key text; current_data jsonb;
 before_value jsonb; after_value jsonb; rev bigint; prior jsonb; scope text; seen text[]:='{}'; token text;
begin
 if not public.crm_has_role(p_workspace::text,array['admin','editor']) then
  raise exception 'Accès en écriture refusé' using errcode='42501'; end if;
 if p_request is null or jsonb_typeof(p_changes) is distinct from 'array' then
  raise exception 'Requête invalide' using errcode='22023'; end if;
 if not exists(select 1 from public.crm_editions where workspace_id=p_workspace and year=p_year) then raise exception 'Année inexistante'; end if;
 -- Sérialiser la courte transaction, sans comparer la révision globale.
 perform 1 from public.crm_v2_status where workspace_id=p_workspace for update;
 if not found then raise exception 'Migration V2 non exécutée'; end if;
 select changes,revision into prior,rev from public.crm_requests where workspace_id=p_workspace and edition_year=p_year and request_id=p_request;
 if found then
  if prior is distinct from p_changes then raise exception 'UUID de requête réutilisé' using errcode='22023'; end if;
  return rev;
 end if;
 for change in select value from jsonb_array_elements(p_changes) loop
  entity:=change->>'entity'; key:=change->>'id';
  if entity is null or not(entity=any(array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones','ledger_entries','ledger_categories','settings','forecast','metadata'])) or key is null or key='' then raise exception 'Table ou identifiant invalide' using errcode='22023'; end if;
  token:=entity||':'||key;
  if token=any(seen) then raise exception 'Fiche répétée dans la requête' using errcode='22023'; end if;
  seen:=array_append(seen,token);
  if not(change ? 'before') or not(change ? 'after') then raise exception 'Version manquante' using errcode='22023'; end if;
  before_value:=nullif(change->'before','null'::jsonb);
  after_value:=nullif(change->'after','null'::jsonb);
  if after_value is not null and jsonb_typeof(after_value)<>'object' then raise exception 'Fiche invalide' using errcode='22023'; end if;
  if entity in ('settings','metadata') and key<>'main' or entity='forecast' and key<>'2027' then raise exception 'Identifiant de réglage invalide'; end if;
  if entity=any(array['exhibitors','contacts','partners','tasks','posts','expenses','ideas','assets','invoices','zones','ledger_entries','ledger_categories']) and after_value is not null and after_value->>'id' is distinct from key then raise exception 'Identifiant incohérent'; end if;
  if entity='metadata' and (after_value is null or after_value->>'schema' is distinct from '1') then raise exception 'Schéma CRM invalide'; end if;
  scope:=case when entity='contacts' then '' else ' and edition_year=$5' end;
  current_data:=null;
  execute format('select payload from public.%I where workspace_id=$1 and id=$2 %s','crm_'||entity,scope) into current_data using p_workspace,key,after_value,auth.uid(),p_year;
  if current_data is distinct from before_value then
   raise exception 'Conflit sur % / % : recharge la fiche avant de réessayer',entity,key using errcode='40001';
  end if;
  if current_data is not distinct from after_value then continue; end if;
  insert into public.crm_history(workspace_id,entity,record_id,before_data,after_data,changed_by,edition_year)
   values(p_workspace,entity,key,current_data,after_value,auth.uid(),p_year);
  if after_value is null then
   execute format('delete from public.%I where workspace_id=$1 and id=$2 %s','crm_'||entity,scope) using p_workspace,key,after_value,auth.uid(),p_year;
  else
   if entity='contacts' then
    insert into public.crm_contacts(workspace_id,id,payload,updated_by) values(p_workspace,key,after_value,auth.uid())
    on conflict(workspace_id,id) do update set payload=excluded.payload,version=crm_contacts.version+1,updated_at=now(),updated_by=excluded.updated_by;
   else
    execute format('insert into public.%I(workspace_id,id,payload,updated_by,edition_year) values($1,$2,$3,$4,$5) on conflict(workspace_id,edition_year,id) do update set payload=excluded.payload,version=%I.version+1,updated_at=now(),updated_by=excluded.updated_by','crm_'||entity,'crm_'||entity) using p_workspace,key,after_value,auth.uid(),p_year;
   end if;
  end if;
 end loop;
 update public.crm_v2_status set revision=revision+1 where workspace_id=p_workspace returning revision into rev;
 insert into public.crm_requests(workspace_id,request_id,changes,revision,edition_year) values(p_workspace,p_request,p_changes,rev,p_year);
 return rev;
end;$$;
revoke all on function public.crm_apply_changes(uuid,uuid,jsonb,integer) from public;
grant execute on function public.crm_apply_changes(uuid,uuid,jsonb,integer) to authenticated;

commit;
